### ISSUE TITLE
add query parameter to show challenge answers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#101]
... because my mind doesn't like to switch between resolving programming issues and answering Units Rates questions.

**Comment by arouinfar** [comment]
👍 

Now I won't have to cheat from the design doc anymore. 😄

**Comment by pixelzoom** [comment]
The new implementation (see new Shopping screen) does this, via `?showAnswers`. No plans to add this to the old implementation, since it will eventually be deleted. Closing this issue as "will not fix".
