### ISSUE TITLE
fix horizontal alignment of challenges

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#104]
In the Shopping screen, challenges are not horizontally centered in the accordion box. Everything is slightly to the right.

![screenshot_04](https://cloud.githubusercontent.com/assets/3046552/19083178/643cb91a-8a1e-11e6-9ac9-9a07401c1e7e.png)

**Comment by pixelzoom** [comment]
And before answering the challenges, the alignment issue is less noticeable, but the questions are all a bit right of center.

![screenshot_05](https://cloud.githubusercontent.com/assets/3046552/19083235/93850e20-8a1e-11e6-8b7a-4644c5cfa803.png)

The problem here is that the edit buttons and the smiley faces need to have the same effective width, so that the questions/answers are horizontally centered.

**Comment by arouinfar** [comment]
@pixelzoom would it be helpful to reduce the width of the edit buttons? They aren't quite as wide in the mockups. Here's a comparison of the latest dev (top) and the mockups (bottom). The edit icon is identically sized. The only difference is the physical size of the button.
![image](https://cloud.githubusercontent.com/assets/8419308/19102240/ec8dec22-8a8b-11e6-8fb1-f242a2c4483c.png)

**Comment by pixelzoom** [comment]
I am going to fix the alignment issue independently of the edit button size (or smile/frown face size), so that we still have the flexibility to resize UI elements without affecting the alignment.

**Comment by arouinfar** [comment]
Sounds good @pixelzoom.

**Comment by pixelzoom** [comment]
The new implementation (see new Shopping screen) does not have this problem. No plans to fix the old implementation, since it will eventually be deleted. Closing this issue as "will not fix".
