### ISSUE TITLE
put numbers on cars?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#108]
Racing Lab screen refers to "Double Number Line 1", "Double Number Line 2", "Rate 1" and "Rate 2".  
To clearly tie the cars into this numbering scheme, how about putting a "1" on the blue car and a "2" on the red car?  E.g.:

![screenshot_09](https://cloud.githubusercontent.com/assets/3046552/19087027/d1b34c16-8a2d-11e6-907e-d910e15a751e.png)

**Comment by arouinfar** [comment]
@pixelzoom the numbers are a great idea. In previous iterations of the racing screen we'd discussed putting numbers on the cars, but I'm not sure why we didn't think to keep them in the current design. Should I update the artwork, or would the number be added in code?

By the way, the blue and the red cars are flipped (red Charger should be car 1). I can't remember if I have raised that issue already or not. If not, let me know, and I'll create a new issue @pixelzoom.

**Comment by pixelzoom** [comment]
Probably more cost-effective at this point to add the numbers in the artwork. 

Issue #111 created to swap the cars.

**Comment by arouinfar** [comment]
Sounds good @pixelzoom. I'll make this change in Illustrator, and send you updated artwork.

**Comment by arouinfar** [comment]
I've added the numbers to the cars, and have emailed the updated asset files to @pixelzoom. 

![image](https://cloud.githubusercontent.com/assets/8419308/19097808/cdf4561a-8a64-11e6-853d-ff8c54d81795.png)

**Comment by pixelzoom** [comment]
@arouinfar Updated files received via email. They look good.

In addition to the files that you sent, there are 2 other assets in GitHub that contain cars: one_car_scene.ai, two_car_scene.ai. These are the icons on the scene-selection radio buttons in the “Racing Lab” screen.

Options:

(1) Update these 2 additional assets. Requires no code changes, but increases size of the sim and requires keeping these assets in sync with future car changes.

(2) Compose the radio button icons programmatically using red_car.png and blue_car.png. Will result in smaller sim size, single asset file for each car, but requires code changes (20-30 minutes).

My recommendation is (2).

**Comment by arouinfar** [comment]
@pixelzoom I forgot about the scene selection icons, my apologies.

I also think (2) is a better long-term solution, so let's go with that.

**Comment by pixelzoom** [comment]
New cars are integrated. Scene selection icons moved to #121. Closing.
