### ISSUE TITLE
hide decimal key on keypad when entering integers?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#109]
When entering a value for an integer field, should we hide the decimal key on the keypad?  For example, when entering the value for "Apples for $4.50" in this challenge on the Shopping screen:

![screenshot_10](https://cloud.githubusercontent.com/assets/3046552/19087978/5fb16f36-8a31-11e6-9ba4-73cac47494fc.png)

Or do you want the student to be able to enter non-integers?

**Comment by arouinfar** [comment]
@pixelzoom I don't think we need to disable the decimal point. In interviews, students did not attempt to enter non-integer values, though it's certainly possible that others may try. I don't think it's particularly harmful if students attempt to enter non-integer values, though.

**Comment by pixelzoom** [comment]
Roger. Closing.
