### ISSUE TITLE
Update touch/mouse areas for scale

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#11]
Currently, the behavior of dragging items on/off the scale is a bit too sensitive.

Let's increase the touch/click area around the scale like so:
![image](https://cloud.githubusercontent.com/assets/8419308/17035123/f4b65c24-4f42-11e6-9b50-901a0ca00616.png)

If the center of the bag is in this region when the bag is released, the bag will land on the scale. To place items back on the shelf, it needs to be dragged out of this region, but not necessarily to the shelf.

In this situation, the bags currently return to the scale. However, with the updated touch area, they would instead return to the shelf.
![draggingbags](https://cloud.githubusercontent.com/assets/8419308/17035264/9916e13a-4f43-11e6-8d83-79fc46c9efb1.gif)

Tagging for design meeting to get feedback from @kathy-phet and @schmitzware.

**Comment by arouinfar** [comment]
As discussed in the 7/21 design meeting, let's move forward with this proposed change.

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/19c07842cc8818a6a8efe880b525a6515583a1dd

**Comment by schmitzware** [comment]
Fixed in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.12/

**Comment by arouinfar** [comment]
Feels good to me! Closing.
