### ISSUE TITLE
swap locations of blue and red cars

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#111]
In https://github.com/phetsims/unit-rates/issues/108#issuecomment-251479175, @arouinfar said

> By the way, the blue and the red cars are flipped (red Charger should be car 1). I can't remember if I have raised that issue already or not. If not, let me know, and I'll create a new issue @pixelzoom.

**Comment by arouinfar** [comment]
Thanks @pixelzoom.

**Comment by pixelzoom** [comment]
Cars and NumberPicker colors swapped, screenshot below, @arouinfar please verify. 

![screenshot_31](https://cloud.githubusercontent.com/assets/3046552/19096451/bcde57a0-8a59-11e6-9b5f-670c037bba57.png)

**Comment by arouinfar** [comment]
Looks great! Thanks @pixelzoom.
