### ISSUE TITLE
marker appears at wrong position when numerator value is entered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#112]
Positioning of markers on the number line seems buggy. When I enter a value for the numerator, it never appears at the expected (i.e., correct) location on the number line. (Entering a denominator value works as expected.) 

Example:
- start sim
- go to Shopping screen
- choose Lemons from combo box
- put 2 bags of lemons on the scale
- press Edit button for numerator of double number line
- enter 2.50, press Enter button
- the marker moves to 1.50, not to 2.50

Screenshot for the above example:
![screenshot_11](https://cloud.githubusercontent.com/assets/3046552/19088651/3e49fa9a-8a34-11e6-98ed-782f929e2637.png)

Is this buggy, or some desired behavior that needs to be explained to me?

**Comment by arouinfar** [comment]
Definitely a bug @pixelzoom. Looks like things were still working in dev.19, with the exception of the desired behavior for overwriting lines (see #50) which had not yet been addressed.

**Comment by pixelzoom** [comment]
The new implementation (see new Shopping screen) does not have this problem. No plans to fix the old implementation, since it will eventually be deleted. Closing this issue as "will not fix".
