### ISSUE TITLE
state of number line is not reliably restored

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#114]
Each item is supposed to save the state of its number line.  This feature seems to be very flakey, and state is not reliably being saved/restored. 

Example:
- start sim
- go to Shopping screen
- put 3 bags of Apples on the scale, number line looks like this:

![screenshot_14](https://cloud.githubusercontent.com/assets/3046552/19089240/b8939d0e-8a36-11e6-93da-3aced6023050.png)
- switch to vegetables scene
- switch back to fruits scene, the number line looks like this, all markers have been lost:

![screenshot_15](https://cloud.githubusercontent.com/assets/3046552/19089267/ca46604a-8a36-11e6-9962-3d369763f77f.png)

@arouinfar Is this indeed a bug? Should the number line indeed be fully restored when switching back to an item?

**Comment by arouinfar** [comment]
Definitely another bug @pixelzoom. The number line should be fully restored when switching between items/scenes.

**Comment by pixelzoom** [comment]
This implementation has been replaced, and the new implementation (see new Shopping screen) has no problem restoring state.  No plans to fix the old implementation, since it will eventually be deleted. Closing this issue as "will not fix".
