### ISSUE TITLE
define terminology for user interface

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#116]
This sim desperately needs to give names to the components of its user interface.  Lack of agreement on what to name things makes it difficult for the team to communicate clearly, and (based my 3 days of working on this sim) has resulted in:

• confusion in GitHub issues (multiple names for the same thing, or the same name for different things)
• confusion in Skype discussions (no words to refer to a UI component)
• lack of clarity in the design document (e.g. multiple semantics for "line")
• different terminology used in code vs discussions (which makes it hard to find things, maintain, etc.)

Here's a visual catalog of the things that need names, with my suggestions for names. Feel free to suggest other names.

(1) number line marker (or just "marker" if the context is clear)

![screenshot_19](https://cloud.githubusercontent.com/assets/3046552/19089999/ce45676a-8a39-11e6-88fb-421fd15bb187.png)

(2) marker editor 

![screenshot_18](https://cloud.githubusercontent.com/assets/3046552/19089982/b8b49056-8a39-11e6-9820-daea31a6ccb7.png)

(3) marker "undo" button

![screenshot_21](https://cloud.githubusercontent.com/assets/3046552/19090018/e4dbddce-8a39-11e6-825c-cd455192dc6b.png)

(4) "clear scale" button

![screenshot_20](https://cloud.githubusercontent.com/assets/3046552/19090040/f93bc252-8a39-11e6-9f7d-e72bb6eafb9f.png)

(5) item combo box, or item menu

![screenshot_22](https://cloud.githubusercontent.com/assets/3046552/19090062/14dc26b4-8a3a-11e6-898b-9bc757ec0acc.png)

(6) scene radio buttons, or scene buttons

![screenshot_23](https://cloud.githubusercontent.com/assets/3046552/19090091/33ebadb8-8a3a-11e6-8909-3c1988612a43.png)

![screenshot_24](https://cloud.githubusercontent.com/assets/3046552/19090102/3dde1068-8a3a-11e6-89cf-a7aaff7f792f.png)

(7) edit button

![screenshot_25](https://cloud.githubusercontent.com/assets/3046552/19090123/56101230-8a3a-11e6-8a94-aa57ed709d67.png)

(8) "start race" button

![screenshot_26](https://cloud.githubusercontent.com/assets/3046552/19090169/775b6958-8a3a-11e6-9732-3b90eb221323.png)

(9) "return to start" button

![screenshot_27](https://cloud.githubusercontent.com/assets/3046552/19090194/8b733e16-8a3a-11e6-8410-56eece4f4060.png)

(10) finish line flag

![screenshot_28](https://cloud.githubusercontent.com/assets/3046552/19090204/9e051cb6-8a3a-11e6-9201-7691e6251808.png)

(11) track marker (or just "marker" if the context is clear)

![screenshot_29](https://cloud.githubusercontent.com/assets/3046552/19090225/ac3f8dc0-8a3a-11e6-9f1a-892abbf5c459.png)

**Comment by arouinfar** [comment]
@pixelzoom thank you for these suggestions. Everything looks good to me, so no changes on my end. 

I have started using this terminology while responding to Git Hub issues, and I will work on updating the design doc tomorrow.

**Comment by arouinfar** [comment]
Terminology has been propagated to the design doc. Thanks again for these suggestions @pixelzoom.

**Comment by pixelzoom** [comment]
👍
