### ISSUE TITLE
challenge data specification?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#117]
The design document has a table titled "Unit Rates & Challenge Prompts".   Questions for @arouinfar:

(1) What are the values shown in red?  E.g.:

![screenshot_30](https://cloud.githubusercontent.com/assets/3046552/19094413/42add21e-8a4d-11e6-814d-7e5ac6d95899.png)

(2) The implementation of this table ([ChallengeData.js](https://github.com/phetsims/unit-rates/blob/master/js/shopping/model/ChallengeData.js)) does not match the specification. It looks like (all?) discrepancies correspond to the red values in the table.  Is this what you would expect?

**Comment by arouinfar** [comment]
@pixelzoom this is being handled in #20. Closing.
