### ISSUE TITLE
Number line marker: rounding error with carrots  9/$1.35

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#12]
A rounding error keeps it from being correct.

**Comment by phet-steele** [comment]
Found for phetsims/tasks/issues/657 😄

**Comment by phet-steele** [comment]
@schmitzware if I enter the denominator first (9), then the numerator (1.35), I get a line placed correctly. However, if I flip that order and enter the numerator then denominator, I get a smaller gray line. Here they are stacked on top of each other, in 1.0.0-dev.11:
<img width="206" alt="screen shot 2016-07-25 at 3 26 27 pm" src="https://cloud.githubusercontent.com/assets/5863899/17118100/849806ee-527c-11e6-81da-ec81ec44f4e5.png">

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/d34f35e0d0950c6e2206c865324208f3c8357735

Slightly different issue/solution.  Good catch!

**Comment by phet-steele** [comment]
👍 in 1.0.0-dev.12
