### ISSUE TITLE
fundamental architectural issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#120]
As I dig deep into this sim, I'm seeing several fundamental architectural issues.  And I believe they are symptomatic of not having the design sufficiently completed before beginning implementation - the developer obviously had to adapt to evolving requirements.

These issues are all somewhat related, so I'm going to try to summarize them all here.

(1) Logic that involves testing the item type

 I see large `switch` and `if-then-else` statements (typically on some property related to an item type) that are indicative of fundamental problems with how the model is structured.   For example, `NumberLine` should be agnostic of what items its related to. Instead, I see this at line 83, where NumberLine has logic for every item type:

``` js
      switch( itemType ) {
        case ItemData.APPLES.type:
          maxUnits = ItemData.APPLES.maxUnit;
          break;
        case ItemData.LEMONS.type:
          maxUnits = ItemData.LEMONS.maxUnit;
          break;
        case ItemData.ORANGES.type:
          maxUnits = ItemData.ORANGES.maxUnit;
          break;
        case ItemData.PEARS.type:
          maxUnits = ItemData.PEARS.maxUnit;
          break;
        case ItemData.CARROTS.type:
          maxUnits = ItemData.CARROTS.maxUnit;
          break;
        case ItemData.CUCUMBERS.type:
          maxUnits = ItemData.CUCUMBERS.maxUnit;
          break;
        case ItemData.POTATOES.type:
          maxUnits = ItemData.POTATOES.maxUnit;
          break;
        case ItemData.TOMATOES.type:
          maxUnits = ItemData.TOMATOES.maxUnit;
          break;
        case ItemData.PURPLE_CANDY.type:
          maxUnits = ItemData.PURPLE_CANDY.maxUnit;
          break;
        case ItemData.RED_CANDY.type:
          maxUnits = ItemData.RED_CANDY.maxUnit;
          break;
        case ItemData.GREEN_CANDY.type:
          maxUnits = ItemData.GREEN_CANDY.maxUnit;
          break;
        case ItemData.BLUE_CANDY.type:
          maxUnits = ItemData.BLUE_CANDY.maxUnit;
          break;
        default:
          assert && assert( false, 'Cannot get max unit of unrecognized type' );
      }
```

This obviously isn't extensive - it's not going to work for new item types, or for race cars. And similar `switch` or `if-then-else` statements appear in (too) many other places:

> Shelf, line 63
> ItemFactoryNode, line 71
> Challenges, lines 182, 300, 378
> ItemComboBox, lines 62, 126
> ShoppingScreenView, lines 130, 165
> ItemRateNode, line 229

Adding a new item type would involve visiting all of the above files - that's a serious problem. Adding a new item type should be a matter of completing 1 specification of that item type, and adding it in 1 place.

(2) Item type information is not encapsulated. 

Information about item types is spread out across multiple data structures and program logic. `ItemData` contains some of the description for each item type. `ChallengeData` contains some more of it.  And program logic (as identified in (1) above) contains functionality that should be encapsulated with each item type.  This makes it difficult to add a new item type, or get a clear picture of everything relevant to an item type. 

(3) Responsibilities are misplaced.

Item types are supposed to retain their state, and when we switch between item types, we see (for example) the state of the number line for that type.  This would suggest that each item type should have its own associated number line.  Instead, there is a single NumberLine instance that attempts to keep track of the relates state for each item type.  This is misplaced responsibility. An item type should be responsible for maintaining its state.

There are also many view Nodes that implement `reset`. Typically, the model and a set of view-specific Properties are all that needs to be reset, and the view updates accordingly. So this is an indication that these Nodes are likely responsible for things that they shouldn't be.

(4) Unnecessary mutability

Instead of 1 NumberLine per item type, there is 1 NumberLine instance that mutates based on the item type.  Most of the view components are similar; there is 1 item combo box that changes what it displays based on what item type is selected.   This is complicates and difficult to get right.  Each item type should have its own set of model and view components, and we see the ones that correspond to the item type that is selected.

**Comment by pixelzoom** [comment]
How (or whether) to address these issues is going to have a dramatic impact on the cost to complete this sim, and the cost of future maintenance.   Assigning to @arouinfar and @ariel-phet so that they are aware of this, and so that we can discuss further.

**Comment by ariel-phet** [comment]
Discussed over email. Current plan is to have @pixelzoom do about ~20 hours of work in addressing these issues, and then re-discuss.

**Comment by pixelzoom** [comment]
I've done the ~20 hours of work suggested. The plan is to move forward with re-architecting the sim.  All of the above issues will be addressed in the new architecture.   No need to track in this issue, making the decision to proceed is sufficient to close this issue.
