### ISSUE TITLE
units on number line markers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#128]
Make number line flexible enough to display units on any marker value.

At 10/6/16 design meeting, there was discussion about whether to label the top value for markers, when the top axis was dollars.  E.g. in [1.0.0-dev.19](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.19/unit-rates_en.html):

![screenshot_51](https://cloud.githubusercontent.com/assets/3046552/19168729/c3454c22-8bce-11e6-864f-bfac431f6962.png)

**Comment by arouinfar** [comment]
Discussed with @pixelzoom over Skype. 

Decision: $ on top axis, no units on bottom axis, implementation will be flexible to add/remove units.

**Comment by pixelzoom** [comment]
We recently decided to remove '$' from the value on the top axis, since we simply cannot afford the horizontal space.  This was specifically called out at 1/12/17 status meeting, and there was no objection.

**Comment by pixelzoom** [comment]
This requirement is reflected in the new implementation of the Shopping screen.  It will not be addressed in the old implementation. 

Closing.
