### ISSUE TITLE
Increase maximum number of major tick marks to 16

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#13]
Originally, the double number lined had been designed to fit 15 major tick marks. However, it looks like there is room to add a 16th line while maintaining the current spacing and font size. 

The extra line has been mocked up in red over a screenshot of the sim. 
![image](https://cloud.githubusercontent.com/assets/8419308/17035541/1b36e272-4f45-11e6-84cc-ec91429d8fba.png)

Having 16 major tick lines would be particularly handy when dealing with bags of 4 items, such as carrots. 
![image](https://cloud.githubusercontent.com/assets/8419308/17035563/422155d4-4f45-11e6-8876-31bb5abe2a28.png)

I realize there may be some occlusion issues if a line is manually added with an off-scale value. However, I think the benefits of a 16th line outweigh the risk of some temporary occlusion.
![image](https://cloud.githubusercontent.com/assets/8419308/17035767/7011a416-4f46-11e6-8a34-27f743bf958d.png)

The 16th line will be black in the sim. Red was used in the mockup to call attention to the proposed change.

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/35fab776f5c51d11450237e22bb1d4eeff069735

**Comment by schmitzware** [comment]
Fixed in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.12/

**Comment by arouinfar** [comment]
@schmitzware the arrow heads on the horizontal lines look too close to the 16th line, and I think it's because the lines themselves are more spaced out than they were in earlier dev versions.

Compare dev.11 (top), dev.12 (middle), and the overlay of the two (bottom)
![image](https://cloud.githubusercontent.com/assets/8419308/17190031/725d64f2-5401-11e6-9c7f-1870e272fbab.png)
![image](https://cloud.githubusercontent.com/assets/8419308/17190046/88ab9cec-5401-11e6-8cc5-bdeb672a3da0.png)

Can you revert the line spacing to what you had in dev.11? Otherwise, it looks good!

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/f4fdcd3e19d0692b3edd1f541ef407fa6706cf02

**Comment by schmitzware** [comment]
![screen shot 2016-07-27 at 1 49 31 pm](https://cloud.githubusercontent.com/assets/694045/17191877/f666c79e-5400-11e6-9908-de54a79cae70.png)

**Comment by arouinfar** [comment]
It looks like you put the 16th tick mark where the 15 was located in dev.11, so the lines are now closer together than they were in dev.11. This is not quite was I asked for @schmitzware, sorry if I was unclear! What I meant to ask for is for the 1-15 lines to stay located as they were in dev.11, and then the 16 gets added to the end (like the first screenshot in this issue).

**Comment by schmitzware** [comment]
No worries, Amy.. Have a look now.
https://github.com/phetsims/unit-rates/commit/1a41b4b2fc41cc81796770be6a45857ef6149d0a

**Comment by arouinfar** [comment]
Looks great! Thanks @schmitzware
