### ISSUE TITLE
randomly select scene and item at startup?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#132]
There's a comment in the code that indicates that (for the Shopping and Shopping Lab screens) the scene and (in the case of Shopping) the item are supposed to be randomly selected at startup "as per current design document".  

@arouinfar Can you shed some light on this?

**Comment by pixelzoom** [comment]
Note to self: Relevant comments are in URShoppingModel and ShoppingScene.

**Comment by arouinfar** [comment]
@pixelzoom that's true for the Shopping Screen. On startup (or reset all), one fruit, one "veggie", and one type of candy should be chosen to be the default item for each scene (e.g. lemons, carrots, and blue candy).  The idea is that we don't want a classroom full of students to be given the same item by default, as unit rates/answers will spread around the classroom more easily. 

Shopping Lab only has one item for each type (apples, carrots, purple candy), so randomization is unnecessary.

**Comment by pixelzoom** [comment]
@arouinfar What about scene selection?

**Comment by arouinfar** [comment]
@pixelzoom scene selection is not randomized, just the default item within each scene. The scenes are deliberately scaffolded, so we want students to start with the first scene. When opening the Shopping screen, the first scene (Fruit) should selected by default, but the particular kind of fruit should be randomly chosen.

**Comment by pixelzoom** [comment]
Got it, thanks.

**Comment by pixelzoom** [comment]
@arouinfar Please verify that this works as desired in http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.29/unit-rates_en.html

**Comment by arouinfar** [comment]
Close, but not quite @pixelzoom. Randomization on startup looks good, but there's something funny happening on reset all. The fruit in the combo box changes, but the item on the shelf does not match (it's actually the fruit that was first chosen on a fresh startup) until switching to a different scene and then coming back to fruit.

![item_randomization](https://cloud.githubusercontent.com/assets/8419308/19654522/e0188926-99d5-11e6-9748-3bf87518a3bc.gif)

**Comment by pixelzoom** [comment]
Got it. This is symptomatic of some underlying architectural issues. Once those are resolved, this problem will do away. The important thing is that the combo box is behaving as desired.  But I'll leave this open until the items shown on the shelf & scale are correct.

**Comment by pixelzoom** [comment]
This is being handled properly in the revised screens.  Also note that randomization can be disabled (for testing) with `?randomEnabled=false`.

Closing.
