### ISSUE TITLE
Background image is on home page but not my woocomerce side

### ISSUE THREAD

**Issue by troubleme** [phetsims/unit-rates#136]
Good morning,

I'm new to the forum. Long story short, I got ripped off by a webdesign company and now I'm trying to put my site together from what I have saved/backed up, I imported it to a godaddy wordpress hosting and I think I have it up and running but I seem to have some images missing in some pages but not in others (my home page). Certain pages (Home page) my background image shows but when I click a product and it takes me to a product page I do not have the background image like I use to. I'm not a webdesigner/builder but I manage to learn many things along the way. Can someone please help?

**Comment by ariel-phet** [comment]
@troubleme you are posting this question in a repository for the PhET Interactive Simulations Project, so I think you have posted in the completely wrong place. We are an educational organization and do nothing of the sort you are referring to. Closing.

**Comment by troubleme** [comment]
where would I go for underscores.me support?

**Comment by ariel-phet** [comment]
@troubleme https://github.com/Automattic/underscores.me
