### ISSUE TITLE
problem with shelf artwork

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#138]
I discovered this while working on aligning items on the shelf. 

The shelf has some issues at its corner joints.  See screenshot below (of shelf.ai) that shows the left joint. The right joint is similar.  It's not a huge problem once this is converted to PNG.   But it does result in different numbers of transparent pixels being added to the left and right edges, so positioning things on the shelf is off by a pixel or so.  So I think this would be good to fix.

I don't know who did the artwork, so assigning to @arouinfar to address.

![screenshot_118](https://cloud.githubusercontent.com/assets/3046552/21965511/b13a30e8-db1e-11e6-98ab-d2ace810f13e.png)

**Comment by pixelzoom** [comment]
shelf.ai is at https://github.com/phetsims/unit-rates/blob/master/assets/shelf.ai

**Comment by pixelzoom** [comment]
Another option... It would be to trivial to draw the shelf programmatically. It depends on how attached you are to the woodgrain look of the shelf.  The woodgrain is barely perceptible in the sim.

**Comment by pixelzoom** [comment]
Here's the new Shopping screen with the shelf rendered using the image (top) and programmatically (bottom, color = `'rgb( 174, 129, 91 )'`).

![screenshot_120](https://cloud.githubusercontent.com/assets/3046552/21965758/97c017e0-db23-11e6-9971-37be755301bf.png)

![screenshot_119](https://cloud.githubusercontent.com/assets/3046552/21965761/a9420dca-db23-11e6-9e0a-4f61eabf7a5a.png)

**Comment by pixelzoom** [comment]
Note to self: Here's the code for drawing the shelf, in case we decide to go that route.

```js
    var shelfWidth = 356;
    var shelfHeight = 17;
    var shelfDepth = 20;
    var perspectiveXOffset = 25;
    var fill = 'rgb( 174, 129, 91 )';
    var frontNode = new Rectangle( 0, 0, shelfWidth, shelfHeight, {
      stroke: 'black',
      fill: fill
    } );
    var topShape = new Shape()
      .moveTo( 0, 0 )
      .lineTo( perspectiveXOffset, -shelfDepth )
      .lineTo( shelfWidth - perspectiveXOffset, -shelfDepth )
      .lineTo( shelfWidth, 0 )
      .close();
    var topNode = new Path( topShape, {
      stroke: 'black',
      fill: fill
    } );
```

**Comment by arouinfar** [comment]
@pixelzoom I'm not really attached to the woodgrain. The screenshots in https://github.com/phetsims/unit-rates/issues/138#issuecomment-272720003 look great to me. From what I understand, using this version of the shelf will address the original issue with the corner joints. If not, please let me know what else you'll need from me.

**Comment by pixelzoom** [comment]
Shelf converted to code.  Closing.
