### ISSUE TITLE
co-locate controls for selecting an item?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#139]
This occurred to me while testing this sim, which involves lots of switching between items to compare things. 

Selecting a Shopping item often requires using 2 controls - a radio button and the combo box.  And it seems odd that those 2 controls are on opposite sides of the screen.  The radio buttons are also a bit close to the Reset All button, which could be an issue on iPad.  And the lower-right corner of the screen generally looks a little cramped to me. E.g.:

![separate](https://cloud.githubusercontent.com/assets/3046552/22234164/33e2015c-e1b3-11e6-9fe0-0ff95d9a4c1a.png)

I'm not sure if there are pedagogical reasons for the above separation of controls.  But co-locating those controls would seem to provide a better user experience for navigating between items - select a radio button and you see the combo box change directly above it.  It reduces the probability of accidentally brushing across the Reset All button on iPad.  And it looks more balanced to my eye. E.g.:

![screenshot_278](https://cloud.githubusercontent.com/assets/3046552/22234101/a622015a-e1b2-11e6-920e-a7937f660c23.png)

Compare in these dev version:

• Controls spread out: [1.0.0-dev.36](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.36/unit-rates_en.html)
• Controls co-located: [1.0.0-dev.37](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.37/unit-rates_en.html)

@arouinfar your thoughts? Something we should run past the design team?

**Comment by pixelzoom** [comment]
If we moved the radio buttons, we'd presumably want to do that for the "Shopping Lab" screen too.  Here's a rough mockup (Photoshop) of how that would look. Right side of the screen looks a little empty, but we could (and probably should!) make the double number line wider.

![screenshot_280](https://cloud.githubusercontent.com/assets/3046552/22234584/6e27ec52-e1b6-11e6-8464-2fb19067b8c1.png)

**Comment by pixelzoom** [comment]
If we moved the radio buttons, we'd presumably want to do that for the "Shopping Lab" screen too.  

Here's what it looks like now. 

![screenshot_281](https://cloud.githubusercontent.com/assets/3046552/22234642/e0597066-e1b6-11e6-8a9d-690b0df5cc92.png)
 
Here's a rough mockup (Photoshop) with the radio buttons at lower left. Right side of the screen looks a little empty, but we could (and probably should!) make the double number line wider.

![screenshot_280](https://cloud.githubusercontent.com/assets/3046552/22234584/6e27ec52-e1b6-11e6-8464-2fb19067b8c1.png)

**Comment by amanda-phet** [comment]
I really like those scene selection/ radio buttons over by the combo box!

**Comment by arouinfar** [comment]
Thanks for your input @amanda-phet! I also like the new location of the scene selection buttons. Thanks for the suggestion @pixelzoom. :)

**Comment by pixelzoom** [comment]
Great. The change was made to the new Shopping screen in https://github.com/phetsims/unit-rates/commit/8cf7826071023f78e45f7d7840abd9617a8e8c67.  And I will use the same location in the new Shopping Lab screen.

Closing.
