### ISSUE TITLE
No line appearing for an answered challenge

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#14]
1. Answer a challenge correctly. A line will appear on the number line
2. Reset All
3. Answer a challenge correctly, from the SAME food selection in step 1 (or Apples). No line will appear on the number line
4. Press Erase. A line will appear for the challenge in step 3.

<img width="1539" alt="screen shot 2016-07-21 at 1 31 30 pm" src="https://cloud.githubusercontent.com/assets/5863899/17036004/8fda4022-4f47-11e6-95b9-04a1af8d0eee.png">

Seen by myself, @brroberts1231, and @arouinfar on OSX 10.11.6 Chrome and Win 7. For phetsims/tasks#657.

Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html
Version: 1.0.0-dev.10 2016-07-21 17:04:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"eaee6dbf","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"a2e4d843","branch":"master"}}

**Comment by arouinfar** [comment]
Good catch @phet-steele. At one point we had decided that correctly answering challenge prompts (other than the unit rate) should not populate the double number line, which is contrary to the behavior here. I'm going to tag this issue for design meeting, so we can discuss the desired behavior.

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.11, closing.
