### ISSUE TITLE
unit rate for Purple Candy exceeds range of spinners in Shopping Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#141]
This design question is related to the Rate accordion box in the Shopping Lab screen. 

The design document specifies that all spinners have range 1-20.  The design document does _not_ specify what the initial default values should be for those spinners. Since the design document tends to describe the Shopping Lab screen in terms of its differences from the Shopping screen, I therefore assumed that the initial values should be equivalent to the unit rates specified for the Shopping screen. So the initial values would be:

Apples:  $0.50 = 1 / 2
Carrots: $0.15 = 3 / 20
Purple Candy: $5.40 = 27 / 5

As you can see, the numerator for Purple Candy (27) is out of range.  The denominator for Carrots (20) is also at the maximum end of the range, but perhaps that's OK.

FYI, the old implementation uses these initial values:

Apples:  $0.50 = 1 / 2
Carrots: $0.40 = 2 / 5
Purple Candy: $5.00 = 5 / 1

Please specify what the initial spinner values should be for each Shopping Lab item.

**Comment by pixelzoom** [comment]
In the meantime, I'm going to increase the spinner ranges to 1-30, so that things don't blow up.

**Comment by pixelzoom** [comment]
In the meantime, I'm going to increase the numerator spinner range to 1-30 for Purple Candy, so that things don't blow up.

**Comment by pixelzoom** [comment]
Scratch that... easiest to change all spinner ranges to 1-30 temporarily.

**Comment by pixelzoom** [comment]
I'm temporarily using range 1-30 for the number in the Rate panel.

@arouinfar If you'd like to test drive:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.39/unit-rates_en.html

**Comment by arouinfar** [comment]
@pixelzoom the default spinner values are still an open question. I don't think that the default rates necessarily need to match the rates from the Shopping screen, but that's a reasonable choice for now.  We will discuss in the next design meeting (most likely next week) and make the final decision. Leaving self-assigned for now.

**Comment by pixelzoom** [comment]
For the time being, both the numerator and denominator now range from 1-30 in the Rate panel, see 
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.40/unit-rates_en.html

**Comment by pixelzoom** [comment]
Something else to consider when choosing the ranges for the Rate spinners...  If the range is too large, changes to the rate may result in no changes to the markers or scale display.  To demonstrate:

1. go to Shopping Lab screen
2. choose Candy scene
3. put 1 bag of candy on the scale
4. set Rate numerator and denominator to 1
5. increase Rate denominator.  As the value gets larger, you'll notice that changing the rate sometimes results in no change to the markers or scale display (because these things don't have enough decimal places to represent the change)

**Comment by arouinfar** [comment]
Here's a matrix of the possible rates with dollars listed in red along the top, and number of items/lbs listed in blue along the side. Within a single row or column the rates (rounded to the nearest hundredths place) are unique, which means the price on the double number line markers and scale will visibly change as one of the spinners is adjusted.

![image](https://cloud.githubusercontent.com/assets/8419308/22612523/6fbe227c-ea2e-11e6-85e4-5a9ebe685018.png)

These rates will work nicely when considering whole numbers of apples or carrots. However, there's an issue when looking at the purple candy. At the rates $1/9 lbs and $1/10 lbs, a bag (0.4 lbs) of candy rounds to the same cost ($0.04).
![image](https://cloud.githubusercontent.com/assets/8419308/22612420/c5cf48ea-ea2d-11e6-9ecc-cc86cb339100.png)

If we limit the spinner ranges to $1-30 and 1-9 items or pounds, the price on the scale (rounded to the nearest cent) will always visually change if one of the spinners is changed. The double number line markers that are added through interaction with the scale will also always visibly change as the one of the spinners is adjusted.  

Even within these spinner ranges, there will still be markers with a dollar value that will not visibly change as one of the spinners is adjusted. This will primarily affect minor markers (for all scenes) and the 0.1, 0.2, and 0.3 lb major markers for candy.

**Comment by pixelzoom** [comment]
@arouinfar said:
> However, there's an issue when looking at the purple candy. At the rates $1/9 lbs and $1/10 lbs, a bag (0.4 lbs) of candy rounds to the same cost ($0.04).

The spinner ranges can be different for each category.  For example, 1-10 for Fruit and Vegetables, and 1-9 for Candy.  I'm not advocating that, just mentioning it in case it's an option that you'd like to consider.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! It's good to know that it's an option, but I'd prefer to keep the spinner ranges consistent across scenes, if possible.

**Comment by pixelzoom** [comment]
At 2/9/17 design meeting, we made the following decisions for the Shopping Lab screen:
• initial values of all spinners will be 1
• range of all spinners will be 1-20

Implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.47/unit-rates_en.html?showAnswers&randomEnabled=false

@arouinfar please review.

**Comment by arouinfar** [comment]
Looks good @pixelzoom. Thanks!
