### ISSUE TITLE
Candy scenes: scale fails ?stringTest=double

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#142]
Observed in dev.39. 

For the candy scenes, the scale does not handle i18n gracefully.
<img width="491" alt="screen shot 2017-01-31 at 4 40 54 pm" src="https://cloud.githubusercontent.com/assets/8419308/22521100/15ccdefe-e874-11e6-84e2-32687d08c047.png">

However, in reality, I don't think that the localized strings would be so dramatically lengthened. For example, I would expect that the currency symbol remains one character and that the weight abbreviation won't be as long as 'lbs' repeated four times.

@pixelzoom I wanted to make you aware of the potential for layout issues. Can you limit the width of the readouts so that they remain within the boundary of the scale?
![image](https://cloud.githubusercontent.com/assets/8419308/22521682/0e90004c-e876-11e6-8370-9355d1e52db2.png)

There still seems to be plenty of room for long strings, and we can scale down the font size once at max width.

**Comment by pixelzoom** [comment]
Thanks for reporting @arouinfar.  When I sent out 1.0.0-dev.39, I should have mentioned that the sim has not yet been tested for i18n.  And the scale is definitely a known issue, which I will be addressing.

**Comment by arouinfar** [comment]
Got it. Thanks @pixelzoom.

**Comment by pixelzoom** [comment]
I addressed the i18n issue, screenshot below. @arouinfar please verify in this dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.40/unit-rates_en.html?stringTest=double

![screenshot_131](https://cloud.githubusercontent.com/assets/3046552/22565596/f65e2fa0-e945-11e6-909c-d7ae7218a0e3.png)

**Comment by arouinfar** [comment]
Looks great @pixelzoom. Thanks!
