### ISSUE TITLE
relocated scene selection buttons in Racing Lab

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#144]
I made a non-trivial layout change in the Racing Lab screen, so wanted to point it out and get approval. I relocated the scene selection buttons (1 vs 2 cars).  You can view this change in [1.0.0-dev.44](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.44/unit-rates_en.html?showAnswers&randomEnabled=false&old).  This frees up a bit of trapped space, moves related controls to the right center, and moves the scene selection buttons away from the Reset All button (so it's not as likely to be brushed accidentally on mobile devices.)  It also looks more balanced to my eye.

Old layout:

![screenshot_292](https://cloud.githubusercontent.com/assets/3046552/22765633/a94f05b6-ee2e-11e6-8ad1-58db46efb604.png)

New layout:

![screenshot_291](https://cloud.githubusercontent.com/assets/3046552/22765637/abfa7840-ee2e-11e6-95c2-6b81c699c0d9.png)

**Comment by ariel-phet** [comment]
I like it....for some reason I feel like I saw a mockup like this at some point.

**Comment by arouinfar** [comment]
Looks good @pixelzoom! @ariel-phet is correct that we had discussed moving the scene selection buttons next to the start race button, but that was after DS had wrapped up his work.
