### ISSUE TITLE
major marker units for Racing Lab screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#145]
@arouinfar What are the desired major marker increments for the Racing Lab screen? Since the denominator (hours) updates when the rate is changed, major markers must be defined in terms of the numerator (miles).

I'm working on this now, so I will proceed with major markers at 10-mile increments (10, 20, 30,...)

**Comment by arouinfar** [comment]
@pixelzoom 10-mile increments seems like a natural choice to me. However, I know we'll run into crowding issues if a student adds all 20 major markers to the DNL, though it may be a somewhat unlikely use case. 

Alternatively, we could use 20-mile or 25-mile increments. The former won't align with the track markers (perhaps not important), and the latter may not offer enough resolution. 

@pixelzoom is this something that you can easily adjust later? I'd like to to play with a version with 10-mile increments, though I'm not sure I can commit to it yet.

**Comment by pixelzoom** [comment]
@arouinfar asked:
> is this something that you can easily adjust later?

Yes, easily adjusted later.

**Comment by arouinfar** [comment]
Good to know @pixelzoom. Thanks!

**Comment by pixelzoom** [comment]
Note to self: Major marker interval is currently set to 25, implemented in RacingLabModel, as an option to DoubleNumberLine:

```js
48    // Specifies the interval for major markers
49    isMajorMarker: function( numerator, denominator ) {
50      return ( numerator % 25 === 0 );
51    }
```

**Comment by pixelzoom** [comment]
After playing around with this... My feeling is that the interval should be the same for the track markers and the major markers on the double number line (DNL).  I also think the track markers are a bit large and perhaps don't need to be yellow (and perhaps not even triangles).

[1.0.0-dev.48](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.48/unit-rates_en.html?showAnswers&randomEnabled=false) has track markers at intervals of 50, major markers on the DNL at intervals of 25. 

[1.0.0-dev.49](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.49/unit-rates_en.html?showAnswers&randomEnabled=false) uses 25 for both intervals, and has a less prominent track marker (smaller black triangles).

@arouinfar your thoughts?

**Comment by pixelzoom** [comment]
Screenshots, with identical configuration and markers:

1.0.0-dev.48:

![screenshot_139](https://cloud.githubusercontent.com/assets/3046552/22997645/7f758c3a-f390-11e6-8c28-f341420589be.png)

1.0.0-dev.49:

![screenshot_138](https://cloud.githubusercontent.com/assets/3046552/22997651/8555b562-f390-11e6-8f06-e5d7f0864170.png)

**Comment by arouinfar** [comment]
Thanks for the recommendations and dev versions @pixelzoom. After playing with dev.48 and dev.49, I think major markers in 25-mile increments feels really natural. I also like the amount of space between the major markers as well. It feels really clean.

![image](https://cloud.githubusercontent.com/assets/8419308/22997677/a6dc335a-f390-11e6-884c-ea3ed43ecb40.png)

I agree that the track markers could be downplayed a bit, but I think that increasing the number of markers gives them too much visual weight. The track markers help the user "eye-ball" distances and can make resizing a bit more efficient. I find it harder to think about the track length when it's split into 1/8ths.

I like the smaller black markers in dev.49, but I'd rather we kept the spacing at 50 miles.

**Comment by pixelzoom** [comment]
[1.0.0-dev.50](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.50/unit-rates_en.html?showAnswers&randomEnabled=false) has:
• 25-mile increments for major markers on DNL
• 50-mile increments for track markers
• smaller black track markers

@arouinfar If this looks OK, you can close this issue.

**Comment by arouinfar** [comment]
Looks great!
