### ISSUE TITLE
singular vs plural units

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#146]
(1) Pickers in all Rate panels: When the value is 1, should the label to switch to singular? (E.g. "1 dollar", "1 Apple", "1 mile", "1 hour".)   Or is it acceptable to use plural in all cases? 

(2) The length of the race track is shown below the finish flag, e.g. "200 miles".   When the length is 1, do you want this label to be "1 mile" or "1 miles"?  If the answer to (1) is to use plural everywhere, then this would be the only usage of "mile".

(3) The race timer displays the time in hours, e.g. "2.00 hours".  When the time is 1 hour, do you want the display to show "1.00 hours" or "1.00 hour".   This is the only place where the string "hour" would appear in the simulation.  Note that if we right justify the display, then  the entire display will shift to the right whenever the timer hits "1.00 hour".  If the answer to (1) is to use plural everywhere, then this would be the only usage of "hour".

For all of the above, it's a nontrivial amount of work to make the units switch between singular and plural.  And it introduces additional strings that must be translated.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar I am fine with sticking to plural

My rationale would be that when we label the axes of a graph/number line we use plural for the units (kilograms or such). I think this is a minor concern and not worth the extra effort/complexity. Although of course appreciate the attention to detail in bringing it up.

Defer to @arouinfar for the final call, but that is my feeling.

**Comment by pixelzoom** [comment]
The only place where we are currently handling singular vs plural units is in the Questions panel. And it's important to do so there, since the units appear in the context of sentences.  But my feeling is that the other situations (1-3 above) are a bit overkill.  But as @ariel-phet said, deferring to @arouinfar.

**Comment by arouinfar** [comment]
@pixelzoom I agree with @ariel-phet on this one -- let's stick with plural. 

As you've pointed out, we make the singular/plural distinction when in the context of sentences in the Questions panel. However, I think when the unit is on its own, it's fine to leave it plural. I would agree that the situations you've outlined lean towards overkill, but I do appreciate the opportunity to make the call.

**Comment by pixelzoom** [comment]
I removed the singular "mile" and "hour" from the string file. Nothing else to do here, so closing.
