### ISSUE TITLE
how to handle creation of race marker when timer is collapsed?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#147]
@arouinfar You mentioned this issue previously, but I don't see an issue for it, so here it is.

When a car reaches the finish line, the design document specifies that a marker is automatically created.  But if the timer is collapsed, that marker's denominator will show the value of the timer.  This defeats the purpose of having a collapsible timer.

Options:

(1) Create a marker regardless of the timer's expanded/collapsed state.  This has zero cost, but makes collapsing the timer ineffective.

(2) Don't create a marker unless the timer is expanded.  This is relatively easy and inexpensive. The downside is that you'll get a marker only if you run the race with the timer expanded.

(3) If the timer is collapsed when the race ends, defer creating the corresponding marker until the timer is expanded. After the timer has been expanded, the marker is shown regardless of the expanded/collapsed state of the timer.  This is not trivial, but doable without touching the implementation of markers.

(4) Create a marker with a '?' in the denominator, which appears/disappears when the timer is collapsed/expanded.  There is currently no support for this in the implementation of markers, and it will be relatively expensive and destabilizing to add.

My recommendation is option (3).

**Comment by pixelzoom** [comment]
Thinking about this more... I'm a bit concerned that option (3) may be a little non-intuitive.  A more straightforward behavior might be better, so changing my vote for option (2).

**Comment by arouinfar** [comment]
@pixelzoom thanks for creating this issue. It's on my list of things to bring up at design meeting tomorrow, but it's good to have a tracking issue for it. I'm leaning towards (2), but I'll see if I can come up with some alternative options.

**Comment by arouinfar** [comment]
Discussed during 2/16/17 design meeting.

Let's go with option (1). If the teacher wants to ask predictive questions, they can minimize the DNL to hide the revealing marker. Teacher Tips and Primer will include this information.

**Comment by pixelzoom** [comment]
No development required for this. So I'm unassigning for now, and labeling with "design:teaching-resources".

**Comment by pixelzoom** [comment]
I move the remaining work on this issue to https://github.com/phetsims/unit-rates/issues/150.  Closing.
