### ISSUE TITLE
rounding is causing marker problems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#148]
Because of the number of decimal places that we're using, we're running into serious problems with markers throughout the sim.   In all screens, we're currently using 2 decimal places for both the numerator and denominator.

The problem is best illustrated via an example, which you can replicate in [1.0.0-dev.51](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.51/unit-rates_en.html?showAnswers).  Follow these steps: 

1. run sim with `?showAnswers`
2. go to Racing Lab
3. set Rate 1 to 66:2
4. use marker editor to enter numerator 100
5. marker editor shows that the corresponding denominator is 3.03
6. enter denominator 3.03
7. marker editor shows that the corresponding numerator is 99.99

So we can't create a marker at 100 - or many other integer mileages.  This is also a problem in the other 2 screens.

If we change the algorithm to allow 100 in the above example, then we create another problem. If the denominator is entered first (e.g. 3.03) then the corresponding numerator is not 100, but 99.99.  So we can end up with 2 markers with identical denominator and different numerators.

To solve this problem in general, the numerator must have fewer decimal places than the denominator.

**Comment by pixelzoom** [comment]
Here's dev version 1.0.0-dev.52, which eliminates the problem: 
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.52/unit-rates_en.html?showAnswers&randomEnabled=false  

The number of decimal places in 1.0.0-dev.52 is as follows:

Shopping, Shopping Lab -
cost: 2
quantity: 3

Racing Lab -
miles: 1
hours: 2

While the problem was definitely less pronounced in the shopping screens, I see no downside to addressing this issue in those screens by _adding_ an additional decimal place to the denominator (quantity).

In Racing Lab, the timer shows 2 decimal places, so I _reduced_ miles to 1 decimal place.

@arouinfar please test drive.

**Comment by pixelzoom** [comment]
@arouinfar reported that 1.0.0-dev.52 still has a problem.  E.g:

1. ?showAnswers
2. Shopping Screen
3. Apples
4. enter denominator 1.25, numerator should be 0.63
5. enter numerator 0.63, rejected, denominator should be 1.26

This smells like a separate issue, I'll investigate.

**Comment by arouinfar** [comment]
@pixelzoom I'm not sure if the number of decimal places in the original denominator has an effect or not, so here's a slightly different example with 1.125 apples.

1. ?showAnswers
2. Shopping Screen
3. Apples
4. Enter denominator 1.125, numerator should be 0.56
5. Enter numerator 0.56, rejected, denominator should be 1.12

**Comment by pixelzoom** [comment]
New dev version: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.53/unit-rates_en.html?showAnswers&randomEnabled=false

I changed the algorithm used by the marker editor. When the second of 2 values is entered for a marker, the editor now determines whether the 2nd value could be computed from 1st.  If yes, then we create a marker. If no, then the 1st value is erased. 

The logic of "numerator must have fewer decimal places than denominator" also does not hold up. So I also revert shopping screens to use 2 decimal places for denominator (quantity).  Decimal places in 1.0.0-dev.53 are as follows:

Shopping, Shopping Lab -
cost: 2
quantity: 2

Racing Lab -
miles: 1
hours: 2

It is still possible to create 2 markers that share a denominator (or numerator) and have a different numerator (or denominator).  I don't know how to get around this issue.  Perhaps if this case occurs, we should remove the older of the 2 markers? 

@arouinfar please have a look.

**Comment by arouinfar** [comment]
@pixelzoom I think this is a reasonable solution. There will still be a few unavoidable edge cases, like this one

?showAnswers
Racing Lab Screen
Rate 1 = 66/2
Enter numerator 199.9, denominator should be 6.06
Enter denominator 6.06, accepted

Use marker editor again
Enter denominator 6.06, numerator should be 200
Enter numerator 199.9, rejected, denominator should be 6.06
Enter denominator 6.06, accepted

![marker_editor](https://cloud.githubusercontent.com/assets/8419308/23038263/a39df654-f446-11e6-8eba-d778732bf7c6.gif)

6.06 hours is an acceptable denominator for two numerators: 199.9 miles and 200 miles. However, if 6.06 hours in entered first, only the 200 miles is acceptable. However, I am fine with this behavior.

In the case with two markers that share the same numerator or denominator, I think we should delete the older of these two markers. It seems problematic to show two seemingly identical times  corresponding to two different distances (or the reverse).

**Comment by pixelzoom** [comment]
@arouinfar said:
> I think this is a reasonable solution. There will still be a few unavoidable edge cases,

Whatever we do is going to be a compromise. I'm convinced that this is an unsolvable problem.

> In the case with two markers that share the same numerator or denominator, I think we should delete the older of these two markers. It seems problematic to show two seemingly identical times corresponding to two different distances (or the reverse).

This change is implemented in [1.0.0-dev.54](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.54/unit-rates_en.html?showAnswers&randomEnabled=false).  

If 2 markers share a term, then:
• If the newer marker has greater precedence (e.g. a question marker) or equal precedence, then the older of the 2 markers is deleted.  
• If the newer marker has lesser precedence, then the newer marker is ignored. 

Example:
1. Shopping screen
2. Apples
3. denominator 1.25 in marker editor
4. numerator 0.63 in marker editor
5. marker is created at 0.63/1.25
6. denominator 1.26 in marker editor
7. numerator 0.63 in marker editor
8. The markers share the same numerator (0.63), and have the same precedence. The older marker (0.63/1.25) is deleted, the newer marker (0.63/1.26) is added.

Back to @arouinfar.

**Comment by arouinfar** [comment]
Looks good @pixelzoom! I hadn't thought about the possibility of the older marker being a question marker, so I'm glad you considered precedence rather than indiscriminately deleting the older marker.
