### ISSUE TITLE
4th challenge prompt issues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#15]
Both of these were after sim load, no fancy procedure necessary These issues may be indicative of a larger problem.

1) This 4th challenge for Apples is a little wrong, it _should_ read $5.00/ 10 Apples, not 10/ 10 Apples. The user input for this challenge happened to be "10", which looks to have just been placed in the numerator (or $5.00 was just rounded up):

<img width="280" alt="screen shot 2016-07-21 at 3 29 01 pm" src="https://cloud.githubusercontent.com/assets/5863899/17039520/29870aec-4f58-11e6-9a83-2b1dd64b5f1d.png">

2) This 4th challenge for Red Candy is a little wrong, too. It _should_ read $1.60/ 8 pounds, not 2/ 8 pounds. Here it just looks like the answer was rounded, and the dollar sign dropped (similar to the Apple challenge above):

<img width="331" alt="screen shot 2016-07-21 at 3 47 20 pm" src="https://cloud.githubusercontent.com/assets/5863899/17039981/7bcf74ea-4f5a-11e6-9355-7a2392f4c11c.png">

Seen on OSX 10.11.6 Chrome. For phetsims/tasks#657.

Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html
Version: 1.0.0-dev.10 2016-07-21 17:04:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"eaee6dbf","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"a2e4d843","branch":"master"}}

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/9b9bd8621b9d4ab9dc81fd156c097aec3007d9ec

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.11, closing.
