### ISSUE TITLE
race markers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#151]
When a car reaches the finish line, a "race marker" is created on the double number line.  The design document doesn't fully specify this feature, so here's what we decided in 2/16/17 design meeting:

• when the car reaches the finish line, a race marker is created on the double number line
• a race marker is created regardless of whether the timer is collapsed (see #147)
• race markers are color-code to car
• pressing the eraser button erases all markers, with one exception: if the car is still at the finish line, its corresponding marker is not erased

**Comment by pixelzoom** [comment]
Implemented as described above in [1.0.0-dev.56](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.56/unit-rates_en.html?showAnswers&randomEnabled=false).

Once you have a few "race markers" on the DNL, it becomes a bit less obvious which marker is associated with the currently location of the car.  So I changed the look of the "car position" indicator on the double number line. The indicator is now a bit thicker. And rather than being the length of a minor marker, it now occupies the vertical space between the 2 number lines.  This makes it clear (but not overbearing) which marker corresponds to the car.  See example in the screenshot below.

@arouinfar please have a look.

![screenshot_141](https://cloud.githubusercontent.com/assets/3046552/23048657/98bff63c-f474-11e6-9ebf-e7d277bdb090.png)

**Comment by pixelzoom** [comment]
@arouinfar Do you think we should use a slightly darker shade of blue for car2's markers? (Would also be applied to car's 2 spinners.)

**Comment by arouinfar** [comment]
@pixelzoom I really like the updated race marker in dev.56! 

I've also been thinking about the light blue used for car 2's markers. I find it a bit hard to read, and I skeptical of how well it will project. That blue works well for the car, where there's a concentrated patch of the color. It was also fine when using the race tracking dot (which also had a black stroke) but I think it's a bit challenging to read the blue text against white.

In this screenshot I've darkened the blue a little bit to (0, 143, 204) in the unnumbered car, right marker, and the miles spinner. 

![image](https://cloud.githubusercontent.com/assets/8419308/23080155/03b76432-f50d-11e6-8b67-24af40cc90cf.png)

Here's another version without the darker car:
![screen shot 2017-02-17 at 12 17 42 pm](https://cloud.githubusercontent.com/assets/8419308/23080209/242c4278-f50d-11e6-92ea-bd67285e090c.png)

I don't particularly like the darker car, but I think that the darker blue in the DNL and spinner looks similar enough to the lighter blue car (especially in the absence of the darker blue car), that it wouldn't be noticeable.

**Comment by pixelzoom** [comment]
@arouinfar The car is a PNG file, so the color used in the code isn't applied to the car.  So I think it's fine to leave the car "as is", and simply darken the markers and spinners.  I'll change to 'rgb(0, 143, 204)'.

**Comment by pixelzoom** [comment]
Car2 is `rub(0,143,204)` in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.57/unit-rates_en.html

@arouinfar please review, close if this looks OK.

**Comment by arouinfar** [comment]
:+1:
