### ISSUE TITLE
pixel polishing for Questions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#152]
A few members of the design team are not happy with the current layout of the Questions accordion box, so we'll do some pixel polishing.  As of [1.0.0-dev.56](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.56/unit-rates_en.html?showAnswers&randomEnabled=false), it looks like this:

![screenshot_294](https://cloud.githubusercontent.com/assets/3046552/23080951/07e75334-f510-11e6-809d-c4f31193c597.png)

**Comment by arouinfar** [comment]
@pixelzoom I can mock up some alternatives later this afternoon.

**Comment by arouinfar** [comment]
Currently, I have a two main concerns with the current layout of the Questions panel.
* There's a lot of trapped space around the edit buttons which competes with the questions.
* There could be a little extra spacing between the correct answer and the next question. When correctly answered, it looks like one question flows directly into the next.

I've mocked up a few alternatives for the Questions panel. In all options, I've moved the edit buttons and challenge refresh button to the right side of the panel. The green check mark will replace the edit button once a question is correctly answered. I've also reduced the spacing between the questions and answers by 2px. The relative <i>vertical</i> spacing between the text box, numbers, fraction bar, etc. has been unchanged.

Here are a few alternatives:
1. Leave questions centered. There's still quite a bit of trapped space around the edit buttons, but the buttons come <i>after</i> the beginning of the sentence, so I find it less bothersome.
![image](https://cloud.githubusercontent.com/assets/8419308/23183391/1529ec06-f839-11e6-87e0-beacdd0998ab.png)

2. Left-align the questions with "Questions" title. This leaves quite a bit of white space beneath the left side of the questions.
![image](https://cloud.githubusercontent.com/assets/8419308/23183401/1e2abc18-f839-11e6-8aa4-2dcfbfe351b6.png)

3. Left-align the questions with "Questions" and move text box/correct answer 10 px to the left.
![image](https://cloud.githubusercontent.com/assets/8419308/23183412/26de1a76-f839-11e6-8ca2-934640819144.png)

I think option (3) is the most aesthetically pleasing, but I recognize it introduces more work, particularly when handling i18n. I think the simplest option would certainly be (1), which I think is still an improvement. I don't particularly like option (2), as it feels a bit unbalanced.

One way to handle i18n would be to allow the string to expand to the right until it hits the right-most boundary (1), and then expand left it hits the left-most boundary (2), and then scale down the font size (3). 
![image](https://cloud.githubusercontent.com/assets/8419308/23183238/98a00d8c-f838-11e6-82fe-c4d8ac69b816.png)

Any thoughts @ariel-phet @pixelzoom?

**Comment by amanda-phet** [comment]
I personally like option (1) quite a bit. It seems odd to me to mix left-aligned questions with centered answers. But I think the suggestion to move the edit button to the right and replace it with a check makes SO much sense!

**Comment by arouinfar** [comment]
Thanks @amanda-phet! I think the reason that I like (3) is that it looks less crowded, though it uses a somewhat wonky alignment. Realistically, I think (1) is the best option, and it's definitely an improvement.

**Comment by pixelzoom** [comment]
I like option (1).  

For all 3 options, the location of the refresh button (lower-right) puts it dangerously close to the Reset All button -- see screenshot in https://github.com/phetsims/unit-rates/issues/152#issue-208539519.  Highly recommended to move it to lower-left.

**Comment by arouinfar** [comment]
Good suggestion @pixelzoom. Here's what option (1) would look like with the refresh button on the left. 
![image](https://cloud.githubusercontent.com/assets/8419308/23190921/2eb44f1c-f858-11e6-8ed2-114355e86abb.png)

Let's keep the button on the left side of the panel.

**Comment by ariel-phet** [comment]
@arouinfar @pixelzoom generally think this is an improvement

One thing I was thinking...not sure if there is any way to make it work, but is there some way the edit button could be in the readout box? The readout box is kind of just a place holder, and don't we have some functionality where tapping the readout box opens the entry keypad? Maybe that idea is crazy, but it seems like if it were able to be executed it could clean things up a little.

**Comment by pixelzoom** [comment]
@ariel-phet asked:
> ... but is there some way the edit button could be in the readout box? ...

Presumably you mean inside the box _with_ the value, and not instead of the value.

This would be inconsistent with the marker editor (and other sims) where the edit button is placed outside the box.

This would also make it impossible to align edit buttons for multiple boxes.  You'd be forced to make all boxes the same width.

**Comment by pixelzoom** [comment]
I'm going to proceed based on the updated version of option (1) shown in https://github.com/phetsims/unit-rates/issues/152#issuecomment-281527166.

**Comment by pixelzoom** [comment]
New layout implemented in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.58/unit-rates_en.html?showAnswers&randomEnabled=false

@arouinfar @ariel-phet please review.

**Comment by arouinfar** [comment]
Looks great! Thanks @pixelzoom. 

@ariel-phet I'll leave the issue open so you also have the chance to review.

**Comment by ariel-phet** [comment]
Looks good, closing
