### ISSUE TITLE
replace keypad workarounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#153]
The next-generation keypad is in the process of being designed and implemented (see phetsims/scenery-phet#283).  We've missed the window to use it in Unit Rates 1.0.0.  So the plan is to integrate it sometime in the future.  Marking this issue as deferred until then.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/projectile-motion/issues/118, the keypad workaround in unit-rates got copied to projectile-motion.

KeypadLayer and KeypadPanel are a workaround.  They are a workaround for the lack of a robust Dialog (phetsims/joist#359) and the lack of closure on the next-gen keypad (phetsims/scenery-phet#283, phetsims/scenery-phet#271).  Rather than factor out "workaround" code, KeypadLayer and KeypadPanel should be replaced when the above-mentioned issues are addressed.  

Given the rate of progress on those issues, they are unlikely to be addressed any time soon.  So this issue remains "deferred".

**Comment by pixelzoom** [comment]
The next-gen keypad will be used in projectile-motion 1.0.0, see https://github.com/phetsims/projectile-motion/issues/127.  Once that has been addressed, I should be able to use the next-gen keypad in unit-rates, using the same approach as projectile-motion.  Still deferred, and low priority, but self-assigning so that it's on my radar.

**Comment by pixelzoom** [comment]
Integration in unit-rates can proceed after issues identified in https://github.com/phetsims/scenery-phet/issues/283#issuecomment-321404395 are addressed.

**Comment by pixelzoom** [comment]
Still pending completing of phetsims/scenery-phet#283.

**Comment by pixelzoom** [comment]
Still blocked pending completion of phetsims/scenery-phet#283.  Unassigning for now.

**Comment by pixelzoom** [comment]
Still blocked as of 7/16/18 because work on next-gen keypad (https://github.com/phetsims/scenery-phet/issues/283) has not been completed.  @ariel-phet @jbphet FYI.

**Comment by jbphet** [comment]
Assigning to @Denz1994 for followup once https://github.com/phetsims/scenery-phet/issues/283 has been addressed.

**Comment by pixelzoom** [comment]
@Denz1994 I'd like to pair with you on this one.  Let me know when you're ready to work on it.

**Comment by jbphet** [comment]
@zepumph is going to take this on, assigning to him.

**Comment by pixelzoom** [comment]
It's been 4.5+ years since the next-gen Keypad was started, and it's still not completed. And it's been 4+ years since this issue was opened to replace NumberKeypad with Keypad in this sim.  Other sims are using Keypad, so I decided to go ahead and use it in this sim.  

Closing.
