### ISSUE TITLE
animation of bags & items pauses when switching screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#155]
Animation of shopping bags and items is currently handled in the model, via `model.step`. In joist's main animation loop, `model.step` is called for the selected screen only.  So when you switch screens, animations for unselected screens are paused. 

A screen currently has no ability to know when it becomes unselected, so we can't can cancel animations that are in progress, or (for example) move bags and items immediately to their destination.

Animating bags and items via TWEEN is not an option, since tracking their positions in the model is essential.  And if https://github.com/phetsims/joist/issues/404 is ever fixed (which is should be), then using TWEEN would also result in paused animation.

What this means for Unit Rates: If you leave a screen while animation of bags/items is in progress, you will see those animations continue when you return to that screen. 

Here's an example, with `?animationSpeed=100` to make it easier to demonstrate:

1. Run http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.57/unit-rates_en.html?animatonSpeed=100&randomEnabled=false
2. Go to Shopping screen
3. Drag a bag of apples to the upper-right corner of the screen
4. While animation of the bag is in progress, switch to Shopping Lab screen
5. Do some activity on the Shopping Lab screen
6. Switch back to Shopping screen. You will see the animation of the bags continue where it left off.

In practice I don't think this is a big deal, because animations occur relatively quickly.  But I wanted you to know that this can happen, and there's currently nothing that I can do about it.   @arouinfar are you OK with that?

**Comment by arouinfar** [comment]
Students have to take the action (by dragging the bag) that would cause the animation, so I don't think it's a big deal if students happen to observe a delayed animation when switching scenes/screens. Let's leave things the way they are @pixelzoom.
