### ISSUE TITLE
implement "reset shelf" button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#156]
Consolidating this from https://github.com/phetsims/unit-rates/issues/86.

The button in question:

![button](https://cloud.githubusercontent.com/assets/3046552/23140141/35e59304-f76d-11e6-80c7-467c953a7d37.jpg)

Desired behavior:

• move any items or bags from scale to shelf
• put all items back into bags 
• disable the button when all items are in bags on the shelf

**Comment by pixelzoom** [comment]
Implemented in [1.0.0-dev.65](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.65/unit-rates_en.html).

@arouinfar please verify.

**Comment by pixelzoom** [comment]
Found a problem with this.  Sometimes a marker will be created when the "reset shelf" button is pressed. Please hold off on verification.

**Comment by pixelzoom** [comment]
Steps to reproduce in 1.0.0-dev.65:

1. Shopping screen, Apples
2. drag 1 bag to scale
3. drag 1 Apple to shelf
4. press "reset shelf" button
5. a marker gets created at 1.00/2

This is happening when `scale.reset` is called in `ShoppingScene.resetShelfAndScale`.

**Comment by pixelzoom** [comment]
Creation of spurious marker fixed in above commit.

[1.0.0-dev.66](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.66/unit-rates_en.html) is ready for review by @arouinfar.

**Comment by arouinfar** [comment]
Looks great! Thanks @pixelzoom.
