### ISSUE TITLE
improve rendering quality for shopping items and bags

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#157]
The images for shopping items and (especially) bags look a little ragged to me. No one has complained about this, but I figured that I should investigate what it would take to use mipmaps, and whether it results in improved quality.

**Comment by pixelzoom** [comment]
Switching to mipmaps would involve changing the `require` statements in ShoppingItemData. E.g.:

```js
27 - var appleBagImage = require( 'image!UNIT_RATES/apple_bag.png' );
27 + var appleBagImage = require( 'mipmap!UNIT_RATES/apple_bag.png' );
```

Since `width` is undefined for the object returned by mipmap, this bit of code needs to change in ShoppingScene:

```js
134 - var bagWidth = URConstants.BAG_IMAGE_SCALE * this.bagImage.width;
134 + var bagWidth = URConstants.BAG_IMAGE_SCALE * this.bagImage[0].width;
```

**Comment by pixelzoom** [comment]
After the above changes, here's the comparison of `image` vs `mipmap` plugin with Chrome.

image (Chrome 56):
![screenshot_146](https://cloud.githubusercontent.com/assets/3046552/23140716/6f685848-f770-11e6-991c-610c1886179d.png)

mipmap (Chrome 56):
![screenshot_145](https://cloud.githubusercontent.com/assets/3046552/23140746/8c3e2024-f770-11e6-9373-ae0e9e0ff2f8.png)

And here's the comparison with Firefox, which typically has the worst image quality.

image (Firefox 50):
![screenshot_148](https://cloud.githubusercontent.com/assets/3046552/23140860/222a4bda-f771-11e6-823c-c6b54e370940.png)

mipmap (Firefox 50):
![screenshot_147](https://cloud.githubusercontent.com/assets/3046552/23140840/0b71d39a-f771-11e6-8baa-6ad9d27e9da5.png)

I see no appreciable improvement in quality by switching to mipmaps.

**Comment by pixelzoom** [comment]
@arouinfar Just wanted you to be aware that I investigated mipmaps. 

If you're happy with the current quality of bags and images, feel free to close this issue.

If for some reason you'd like the image quality to be improved, we could investigate creating the PNG files at a size closer to what is needed by the sim.  Images for all bags and items are currently scaled by 50%. We may seem an improvement if we reduce the programmatic scaling.

**Comment by arouinfar** [comment]
Thanks for looking into this issue @pixelzoom. I don't really notice a difference between the mipmap and image screenshots you've provided. I took a look at dev.57 in the Chrome 56 and Firefox 51, and I think the image quality looks pretty good, though Firefox is slightly worse (but still acceptable). 

I tried exporting the bag assets from Illustrator at the exact resolution used in the sim, but I think these look a bit more aliased than what's in the sim now.  I'm happy with the artwork as it is now, but @pixelzoom if you would like to pursue this further with the images below, go for it.  


![lemon_bag](https://cloud.githubusercontent.com/assets/8419308/23179584/aaea4d8e-f82b-11e6-8b15-78a1e8f6781e.png) ![orange_bag](https://cloud.githubusercontent.com/assets/8419308/23179585/aaeb77cc-f82b-11e6-8433-0bd8056481b7.png) ![pear_bag](https://cloud.githubusercontent.com/assets/8419308/23179580/aae85452-f82b-11e6-874c-6be788b6d05b.png) ![apple_bag](https://cloud.githubusercontent.com/assets/8419308/23179590/aaf6c4ec-f82b-11e6-8f94-efda5918d252.png)

![carrot_bag](https://cloud.githubusercontent.com/assets/8419308/23179582/aae92b2a-f82b-11e6-9b13-be7206aa1903.png) ![cucumber_bag](https://cloud.githubusercontent.com/assets/8419308/23179583/aaea151c-f82b-11e6-81ef-96d95f253a12.png) ![potato_bag](https://cloud.githubusercontent.com/assets/8419308/23179586/aaf416fc-f82b-11e6-8e73-9ff7b4184906.png) ![tomato_bag](https://cloud.githubusercontent.com/assets/8419308/23179589/aaf65188-f82b-11e6-969c-510b470ff5e0.png)

![green_candy_bag](https://cloud.githubusercontent.com/assets/8419308/23179581/aae8720c-f82b-11e6-955f-dbf42dbcbc02.png) ![purple_candy_bag](https://cloud.githubusercontent.com/assets/8419308/23179587/aaf4f018-f82b-11e6-9a72-38df45844dec.png) ![red_candy_bag](https://cloud.githubusercontent.com/assets/8419308/23179588/aaf5768c-f82b-11e6-83ce-364b3af64d02.png) ![blue_candy_bag](https://cloud.githubusercontent.com/assets/8419308/23179591/aaf8c1ca-f82b-11e6-8e39-4850798d1265.png)

Back to you @pixelzoom, but please feel free to close if you don't wish to pursue this any further.

**Comment by pixelzoom** [comment]
I'm going to leave as is, closing this issue. If anyone complains, we'll reopen this issue.
