### ISSUE TITLE
'lbs' vs 'pounds' on scale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#158]
It still bothers me (a tiny bit) that the Shopping Lab screen displays "pounds" on the Rate panel and DNL, but "lbs" on the scale.  E.g.:

![screenshot_150](https://cloud.githubusercontent.com/assets/3046552/23224569/24e9f02e-f8ec-11e6-9820-1a229efa2432.png)

Is there any reason why we don't display "pounds" on the scale? We certainly have room to do so (see screenshot below).   And while I appreciate that a real-life scale would probably say 'lbs', I'm skeptical that this detail is really relevant or useful here.  Do we think that translators will really want to differentiate between "grams" and "g" for the scale? 

![screenshot_151](https://cloud.githubusercontent.com/assets/3046552/23224655/77b3913e-f8ec-11e6-8728-ee6b4e2c1d57.png)

**Comment by pixelzoom** [comment]
Maybe if I think of this in the same way as 'dollars' vs '$', then I can ignore it :)

**Comment by ariel-phet** [comment]
It is a fair point @pixelzoom, not tagged on this issue, but personally will defer to @arouinfar and @amanda-phet . The main rationale I can see for "lbs" is that is a bit more real world in terms of scales usually have abbreviated units.

**Comment by pixelzoom** [comment]
If we're concerned about "real world"... Most scales display "lb", not "lbs".

**Comment by arouinfar** [comment]
In general, I like the abbreviated unit (either "lb" or "lbs") because it's less cluttered and more realistic. 

My concern with using "pounds" is that it may become pretty long when internationalized, e.g. "kilogramm" or "quilogramos". @pixelzoom can you send a screenshot of the scale with "pounds" with `?stringTest=double`? If it looks reasonable, I would be willing to kill the abbreviated unit.

**Comment by pixelzoom** [comment]
> @pixelzoom can you send a screenshot of the scale with "pounds" with `?stringTest=double`?

This wasn't easy to do, because `stringTest` also doubles the placeholders, so you end up with "0.8 pounds:pounds: 0.8 pounds:pounds" instead of "0.8 pounds:pounds".   But I hacked something together to show what you're likely interested in, and here's a screenshot:

![screenshot_154](https://cloud.githubusercontent.com/assets/3046552/23227494/5cf2fa74-f8f6-11e6-9287-509954d1452d.png)

**Comment by arouinfar** [comment]
@pixelzoom thanks for the `stringTest` hack! I'd forgotten that `stringTest=double` essentially quadruples the string "0.8 pounds". 

After seeing a longer string in context, I could live with "pounds", though I'd still prefer "lbs" (or "lb").  Any thoughts @amanda-phet?

**Comment by pixelzoom** [comment]
After seeing a longer string in context, I'm starting to care less about this :)

**Comment by arouinfar** [comment]
@pixelzoom let's stick with "lbs" then. :)

**Comment by pixelzoom** [comment]
Nothing to do then. Closing.
