### ISSUE TITLE
iPad button discoloration

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#16]
The Edit buttons and Return button are not one solid color (unlike the desktop version). 
![img_0001](https://cloud.githubusercontent.com/assets/5863899/17064627/a678158a-4ffa-11e6-9268-c0f22a732837.PNG)
![img_0001](https://cloud.githubusercontent.com/assets/5863899/17064641/bb6b5b6e-4ffa-11e6-826c-1ea5e8eeaae4.PNG)

Seen on Dalton (iPad Air 2, iOS 10 Beta 2). For phetsims/tasks#657.

Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html
Version: 1.0.0-dev.10 2016-07-21 17:04:55 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 10_0 like Mac OS X) AppleWebKit/602.1.40 (KHTML, like Gecko) Version/10.0 Mobile/14A5309d Safari/602.1
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 95.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"eaee6dbf","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"a2e4d843","branch":"master"}}

**Comment by brroberts1231** [comment]
Not seen on Tycho, iPad 2, iOS 9.3.3

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/29e3827fdaf0f39c05f80f33efb94e5f1b10b672

**Comment by phet-steele** [comment]
@schmitzware it looks like this is going to be an iOS 10 Beta problem not specific to this sim, tracked here phetsims/scenery/issues/556.
