### ISSUE TITLE
when should cost be collapsible?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#162]
@arouinfar Why is cost collapsible in the Shopping Lab screen, but not in the Shopping screen?  I'm asking because I'm curious, and because having it the same in both screens would be a significant code simplification.

**Comment by arouinfar** [comment]
The most likely use case for the collapsible price would be to predict the cost of some number of items, given the rate. In the Shopping screen, the unit rate is initially unknown and is something that needs to be "figured out", while in the Shopping Lab, the rate is directly controlled. While I think the Shopping Lab is the more natural place for these sorts of predictive questions to take place, I could imagine that a teacher may ask predictive questions on the Shopping screen after the unit rate has been determined. 

I think the collapsible price will make the Shopping screen more flexible without any detrimental side effects, pedagogically speaking. @pixelzoom please go ahead and make the cost collapsible on both screens.

**Comment by pixelzoom** [comment]
@arouinfar please verify in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.61/unit-rates_en.html?showAnswers&randomEnabled=false

Cost is now collapsible on both Shopping and Shopping Lab screens -- and I think it's a good thing that the scale now works identically in both screens. (This is still configurable in the code, in case you decide that you don't like it.)

**Comment by arouinfar** [comment]
Looks great! 👍
