### ISSUE TITLE
change delta for "miles" picker

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#163]
Change request from @arouinfar ...

In Racing Lab screen, make the picker for the rate's numerator (miles) increment and decrement by 5.  The delta is currently 1 (the default for NumberPicker).

**Comment by pixelzoom** [comment]
There's a bit of common code work required to complete this change request, see https://github.com/phetsims/scenery-phet/issues/292.

**Comment by pixelzoom** [comment]
Completed in [1.0.0-dev.62](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.62/unit-rates_en.html). @arouinfar please review.

**Comment by arouinfar** [comment]
:+1:
