### ISSUE TITLE
pixel polish Rate accordion boxes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#164]
@arouinfar requested that the Rate accordion boxes should be top aligned with their associated DNL accordion boxes.   And while I'm at it, increase the vertical margins in the Shopping Lab's Rate accordion box, so that the numerator spinner isn't so close to the expand/collapse button.

Before (1.0.0-dev.61):

![screenshot_156](https://cloud.githubusercontent.com/assets/3046552/23336165/c2895eb0-fb84-11e6-8659-2d5bc72b862c.png)

![screenshot_155](https://cloud.githubusercontent.com/assets/3046552/23336164/bd3bfad0-fb84-11e6-9fd0-67f2407c7ff3.png)

**Comment by pixelzoom** [comment]
After, in [1.0.0-dev.62](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.62/unit-rates_en.html). @arouinfar please review.

![screenshot_158](https://cloud.githubusercontent.com/assets/3046552/23336172/fe9ce958-fb84-11e6-8431-12dafa9e894e.png)

![screenshot_157](https://cloud.githubusercontent.com/assets/3046552/23336171/fbe55c18-fb84-11e6-998a-fc67752b121f.png)

**Comment by arouinfar** [comment]
Love it! Thanks @pixelzoom.
