### ISSUE TITLE
pixel polish: shelf color

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#166]
The current shelf color (`'rgb( 174, 129, 91 )'`) doesn't look great to me, a bit dark/saturated, and darker items (especially red items, like apples) don't really "pop":

![screenshot_163](https://cloud.githubusercontent.com/assets/3046552/23535014/e4bfc698-ff78-11e6-8bee-de524e19ee93.png)

Want to try some other colors? Here's `'rgb( 232, 201, 166 )'`, the color of the shelf in energy-forms-and-changes:

![screenshot_164](https://cloud.githubusercontent.com/assets/3046552/23535072/5518f4c8-ff79-11e6-87ee-4144c0b86cc8.png)

**Comment by pixelzoom** [comment]
For example, `'rgb( 232, 201, 166 )'` is used in [1.0.0-dev.64](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.64/unit-rates_en.html?showAnswers&randomEnabled=false).

**Comment by pixelzoom** [comment]
For context...

`'rgb( 174, 129, 91 )'` (dark brown) is used in [1.0.0-dev.63](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.63/unit-rates_en.html?showAnswers&randomEnabled=false).

`'rgb( 232, 201, 166 )'` (tan) is used in [1.0.0-dev.64](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.64/unit-rates_en.html?showAnswers&randomEnabled=false).

**Comment by arouinfar** [comment]
@pixelzoom I think the lighter-colored shelf looks much better. Thanks for the suggestion!

**Comment by pixelzoom** [comment]
Excellent, closing.
