### ISSUE TITLE
marker editor doesn't move immediately to 'home' position on Reset All

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#169]
If you push the 'Reset All' button in a scenario like this:

![screenshot_170](https://cloud.githubusercontent.com/assets/3046552/23624691/e0bc17f2-0263-11e7-9e22-80533e8d67b6.png)

... the marker editor will _animate_ back to its home position (left of the double number line), rather than move there immediately.  This is because the marker location is handled in the view using TWEEN.   This could be changed, but it involves either (a) adding complicated code to cancel the TWEEN animation, or (b) replacing TWEEN with animation in the model.   Since this seems generally unnecessary, I'm inclined to do neither, and just note the decision in this issue.

@arouinfar If you disagree, let me know and I'll try to address this. Otherwise please close.

**Comment by arouinfar** [comment]
Thanks for letting me know @pixelzoom. I don't think this is anything we need to be worried about.
