### ISSUE TITLE
Update the scale readout when removing objects

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#17]
@arouinfar @schmitzware It would make more sense if the scale readout updated based on what is visually on it. Grabbing food from the scale would decrease the scale's displayed value instantly. In the video below, the scale should read $0.00 as soon as I grab the tomatoes (instead it stays as $1.20 until they are returned to the shelf):

![ur01](https://cloud.githubusercontent.com/assets/5863899/17065044/ff7c63be-4ffc-11e6-887d-2cd83601564b.gif)

Seen on OSX 10.11.6 Chrome. For phetsims/tasks#657.

Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html
Version: 1.0.0-dev.10 2016-07-21 17:04:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"eaee6dbf","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"a2e4d843","branch":"master"}}

**Comment by arouinfar** [comment]
Great suggestion @phet-steele! Please make this change @schmitzware.

**Comment by schmitzware** [comment]
The scale readout now updates immediately on an item drag.
https://github.com/phetsims/unit-rates/commit/9736b8fafd25244cc10bafc284bb12489c7128bd

**Comment by arouinfar** [comment]
Looks good!
