### ISSUE TITLE
implications of PhET-iO instrumentation on memory management

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#172]
This sim has a huge number of model items. So it minimizes the size of the scene graph by destroying and reconstructing pieces of the view when the selected item (Apples, Carrots, etc) changes.  This keeps things like Reset All responsive, and simplifies the implementation of view components. 

The tradeoff is that it complicates memory management, compared to approaches where the view persists for the lifetime of the sim.  One needs to implement `dispose` correctly, and that's not an easy task, especially when large parts of common code don't do it properly.  So (as evidenced by https://github.com/phetsims/unit-rates/issues/170) it's going to take some work to plug memory leaks.

What has me concerned is the eventual impact of PhET-iO instrumentation on memory management.  There are many things (like sun buttons) that currently do not need a `dispose` call.  But it seems like just about *everything* that involves a tandem will need a `dispose` call once the sim is instrumented.   And that is very likely to introduce memory leaks, requiring memory management to be revisited.

@samreid Can you comment on this? Is this indeed the case?

**Comment by samreid** [comment]
> This sim has a huge number of model items.

Can you be more quantitative about this? I'm not too familiar with the sim.

> So it minimizes the size of the scene graph

You are saying that with a larger scene graph causes performance problems?  On all platforms or just iPad?

**Comment by pixelzoom** [comment]
The issue here is not the design of Unit Rates.  Let's assume that we have a generic sim that changes the scenegraph as the sim is exercised, and therefore needs to implement `dispose`.  Does adding PhET-iO instrumentation require disposing of additional things (e.g. buttons, other common-code components) that did not need to be disposed of before instrumentation?

**Comment by pixelzoom** [comment]
... and does instrumentation potentially create memory leaks that will occur only when running the sim with PhET-iO enabled?

**Comment by samreid** [comment]
> Does adding PhET-iO instrumentation require disposing of additional things (e.g. buttons, other common-code components) that did not need to be disposed of before instrumentation?

Yes.  For instance, imagine an "add electron" button that disappears when the user is in Mode B.  If you go back to Mode A, then back to Mode B and create a new "add electron" button, there will be a problem if the original "add electron" button was never disposed.  PhET-iO will report a problem that two different instances cannot be assigned the same tandem.  The normal solution to this problem is (a) disposing the items appropriately or (b) persisting them for the life of the sim (reusing the same button instance).

> But it seems like just about *everything* that involves a tandem will need a `dispose` call once the sim is instrumented. 

That is true for items that don't persist for the life of the sim.  If an registered item doesn't call `Tandem.removeInstance` it will incorrectly appear in the list of available objects.

**Comment by pixelzoom** [comment]
Recommended to expand the documentation on how instrumenting affects memory management, see https://github.com/phetsims/phet-io/issues/1073.

Unanswered question in https://github.com/phetsims/unit-rates/issues/172#issuecomment-284788143:
> ... and does instrumentation potentially create memory leaks that will occur only when running the sim with PhET-iO enabled?

**Comment by samreid** [comment]
> ... and does instrumentation potentially create memory leaks that will occur only when running the sim with PhET-iO enabled?

If objects are continually created and registered with tandem and never removed from the tandem registry, it will result in a memory leak.

**Comment by pixelzoom** [comment]
If I have a sim that is instrumented for PhET-iO, will potential tandem leaks show up only when running with PhET-iO enabled?  I.e., do I need to do memory leak testing with PhET-iO enabled?

**Comment by samreid** [comment]
The phet-io/tandem registry only exists when PhET-iO is enabled.  When running in phet brand, this memory leak won't be possible.

**Comment by pixelzoom** [comment]
Thanks, question answered. Closing.

**Comment by pixelzoom** [comment]
Noted in https://github.com/phetsims/phet-info/issues/43 that the code-review checklist should be revised to indicate that memory leak testing must be done with PhET-iO enabled for instrumented sims.
