### ISSUE TITLE
It's too hard to place objects on the scale

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#174]
The scale is very unforgiving while placing items on it. It appears the entirety of an item must be above a threshold screen position (denoted by a red line in the screenshot below) to be placed on the scale. If any part of an item is below this threshold, it gets returned to the shelf. 
<img width="670" alt="screen shot 2017-03-07 at 10 50 14 am" src="https://cloud.githubusercontent.com/assets/5863899/23670347/a5573784-0324-11e7-8504-ef2e3f31ece5.png">

I'll defer to @arouinfar on this, but I think this is pretty clunky. For example, the center apple below would be returned to the shelf since it is just ever so slightly below the threshold:
<img width="656" alt="screen shot 2017-03-07 at 10 59 09 am" src="https://cloud.githubusercontent.com/assets/5863899/23670511/2fc41f22-0325-11e7-94fa-c12a3b7d14c9.png">

I would imagine the "rule" should be reversed. Instead of an _entire_ item needing to be above the threshold, it should be: as long as _any_ part of an item is above the threshold. Note I am saying "item" to mean anything that can be placed on the scale, including bags.

Another thought, we may go as far as to lower the threshold line to be along the bottom of the entire scale image? So any item hovering over the scale would go onto the scale. This:
<img width="670" alt="screen shot 2017-03-07 at 10 50 14 am" src="https://cloud.githubusercontent.com/assets/5863899/23670902/89df8680-0326-11e7-98d4-80dfe6466cfc.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#797.
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.68/unit-rates_en.html
Version: 1.0.0-dev.68 2017-03-07 05:58:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"e0b1c391","branch":"master"},"babel":{"sha":"88805de4","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"43ca9ac4","branch":"master"},"dot":{"sha":"16c2f26b","branch":"master"},"joist":{"sha":"695d3638","branch":"master"},"kite":{"sha":"f4c67cff","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"49b5cb0d","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"04879a99","branch":"master"},"scenery-phet":{"sha":"0bb107fe","branch":"master"},"sherpa":{"sha":"98566566","branch":"master"},"sun":{"sha":"dc8dcfbf","branch":"master"},"tandem":{"sha":"45e9ee17","branch":"master"},"twixt":{"sha":"2ffed75c","branch":"master"},"unit-rates":{"sha":"4712352f","branch":"master"}}

**Comment by pixelzoom** [comment]
You are correct -- the rule is currently that the bottom of the item must be above the top surface of the scale.   Relatively easy to change if we want to change the requirement.

**Comment by pixelzoom** [comment]
Btw... The current rule is optimized so that it's easy to "flick" items off of the scale.  So careful if/when we change the rule - any changes to make it easier to put items _on_ the scale will make it more difficult to take items _off_ the scale.   For this reason, I really don't recommend moving @phet-steele's "threshold line" to the bottom of the scale image.

**Comment by phet-steele** [comment]
@pixelzoom Good point! It really was just a secondary thought, anyway.

**Comment by pixelzoom** [comment]
Note to self:  If we change this, here's what needs to be changed.

```js
// BagDragHandler, line 92
var isAboveScale = ( bag.locationProperty.value.y < scale.location.y + ( scale.depth / 2 ) );

// ShoppingItemDragHandler, line 84
var isAboveScale = ( item.locationProperty.value.y < scale.location.y + ( scale.depth / 2 ) );
```

**Comment by pixelzoom** [comment]
@phet-steele said:
>  Instead of an entire item needing to be above the threshold, it should be: as long as any part of an item is above the threshold. 

Hmmmm... That would actually be a little difficult.  Bags and items know about their location, which corresponds to their bottom-center.  But they currently know nothing about their height.  And that height is not readily available in the model - it is based on the image file used, and the scaling applied to the image.

An easier change would be to simply move the "threshold line" down the same amount for all items, some constant number of pixels below the front edge of the scale's top surface.  But again, that will make it more difficult to "flick" items off of the scale.

**Comment by arouinfar** [comment]
I think the threshold for placing items on the scale is too restrictive, and that these failed attempts make the sim feel buggy.
![shelf_sensitivity](https://cloud.githubusercontent.com/assets/8419308/23720635/71393dd4-03fc-11e7-9fd0-0842277b7b99.gif)

I also got some feedback from Susan that students using Chromebooks (which generally have poor trackpads) struggled to put items on the scale. I would personally move the threshold line down to the middle of the price like so:
![image](https://cloud.githubusercontent.com/assets/8419308/23720778/f3ce01a8-03fc-11e7-97de-be32a254a97f.png)

I appreciate that this will making flicking items off the scale a bit tricker, but the distance to drag an item off the scale (green line) will still be much shorter than to place an item onto the scale (blue line).
![image](https://cloud.githubusercontent.com/assets/8419308/23721074/e511b6e0-03fd-11e7-8b17-3c45e294fb6e.png)

**Comment by arouinfar** [comment]
> Instead of an entire item needing to be above the threshold, it should be: as long as any part of an item is above the threshold.

@phet-steele's suggestion is nice, but given the added complexity, I think it's fine to to keep the reference point at the bottom center of the object.

**Comment by pixelzoom** [comment]
The threshold line has been moved as shown in the screenshot below. Run with `?dev` to display the line.  @arouinfar @phet-steele please verify in [1.0.0-dev.69](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.69/unit-rates_en.html).

![screenshot_176](https://cloud.githubusercontent.com/assets/3046552/23726886/2ebc892c-0413-11e7-9759-ab00673af1c3.png)

**Comment by arouinfar** [comment]
Feels much better @pixelzoom! I have interviews scheduled for tomorrow, so I'll leave this open and self-assigned to watch out for any issues.

**Comment by arouinfar** [comment]
Everything was fine in iPad interviews, so I think it's safe to go ahead and close this.
