### ISSUE TITLE
Use of StopSignNode in Racing Lab Screen.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#175]
Currently, the StartStopButton in the Racing Lab Screen uses an image to render the stop sign on the button. Perhaps using the StopSignNode would be a better approach.

_Thoughts_
- Limited use of images that don't render as well in the FireFox browser
- Use of common code for consistency in code development
- Flexibility in adjusting parameters of  the stop sign in cases of future maintenance.

Here is some sample code tested in StartStopButton.js:
```js
 var StopSignNode = require( 'SCENERY_PHET/StopSignNode' );
 var stopSignNode = new StopSignNode();
 BooleanRoundToggleButton.call( this, stopSignNode, goIcon, runningProperty, options );
``` 
**Stop Sign Produced with above code**
![image](https://cloud.githubusercontent.com/assets/13894380/23682019/dbd1cd90-034e-11e7-8fb6-babb5bb8ccba.png)

@pixelzoom

**Comment by pixelzoom** [comment]
Good idea - I wasn't aware that such a node exists.  I don't see `SCENERY_PHET/StopSignNode'.  Are you by any chance using the one in masses-and-springs?

**Comment by Denz1994** [comment]
I just added it to the repo recently so you may need to do a pull.

**Comment by pixelzoom** [comment]
I did a pull of scenery-phet, don't see it. Are you on a branch?

**Comment by Denz1994** [comment]
Good advice. Try now.

**Comment by pixelzoom** [comment]
Got it, thanks. I'll have a look at integrating it into Unit Rates.

**Comment by pixelzoom** [comment]
Code review #159

**Comment by pixelzoom** [comment]
@arouinfar Should the stop sign be pure red `'rgb( 255, 0, 0 )'`, or should we be using PhetColorScheme.RED_COLORBLIND, `'rgb( 255, 85, 0 )'`.

**Comment by arouinfar** [comment]
Good question @pixelzoom. I'd go with pure red, as that's truer to the color of a real stop sign.

**Comment by arouinfar** [comment]
In the colorblind preview modes, I think pure red has sufficient contrast.
![image](https://cloud.githubusercontent.com/assets/8419308/23721762/211ce392-0400-11e7-8e56-2c8fcfaf6551.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/23721770/295435ce-0400-11e7-9399-e717de537f97.png)

**Comment by pixelzoom** [comment]
I've replaced stop_button.png with StopSignNode in the above commits.

@Denz1994 Note that I also did some cleanup of StopSignNode.  Please review, then feel free to close this issue.  Note that (in general) a function (like `createStopSignPath`) that don't require access to constructor fields should be defined _outside_ of the constructor, otherwise every instance of the type gets a copy of the function.

Feel free to close this issue after reviewing.

**Comment by Denz1994** [comment]
Ahh, I see. Good to know.
