### ISSUE TITLE
i18n problem with cost display on scale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#176]
The cost display on the scale currently assumes that the currency symbol appears at the beginning of the cost, e.g. "$1.00".   But that's a bad assumption, since many countries put the currency symbol after the value, e.g. "20,50 €". 

The order is controlled by this string:

```js
  "pattern_0cost": {
    "value": "${0}"
  },
```

If the symbol is moved to the end of the string, it is currently not shown on the scale.

@arouinfar  Design issue: If the currency symbol is at the end of the string, how do we deal with this on the scale when it is displaying the extra decimal place?

**Comment by phet-steele** [comment]
@pixelzoom I was just about to make an issue about `?stringTest=rtl`. Is this screenshot what you just described?

<img width="650" alt="screen shot 2017-03-08 at 11 34 45 am" src="https://cloud.githubusercontent.com/assets/5863899/23718038/5899e37c-03f3-11e7-94cd-fb58375bd45d.png">

**Comment by pixelzoom** [comment]
Code review #159

**Comment by pixelzoom** [comment]
@phet-steele Sounds like a related issue, but not sure - I don't grok that character set.  What was the string that you used?

**Comment by arouinfar** [comment]
> @arouinfar Design issue: If the currency symbol is at the end of the string, how do we deal with this on the scale when it is displaying the extra decimal place?

In this situation could the currency symbol be given the right-most slot on the scale?

If the price has two decimal places, there would be a space between the number and currency symbol like so:
25,00 €

Otherwise, it would look like this:
25,125€

**Comment by phet-steele** [comment]
> What was the string that you used?

`?stringTest=rtl` can be found in chipper's initialize-globals.js. The string it uses is:
 
\u202b\u062a\u0633\u062a (\u0632\u0628\u0627\u0646)\u202c

This is all I know.

**Comment by pixelzoom** [comment]
@arouinfar asked:
> In this situation could the currency symbol be given the right-most slot on the scale?

Yes. But it's going to make a complicated implementation even more complicated.  But I can't think of any other alternative, so I'll proceed with that.

**Comment by arouinfar** [comment]
> This is all I know.

@phet-steele  FYI, the string literally says "Test (Language)" in Persian.

**Comment by arouinfar** [comment]
> Yes. But it's going to make a complicated implementation even more complicated. But I can't think of any other alternative, so I'll proceed with that

@pixelzoom the only alternative I can think of would be to not allow localization of the ordering of the currency symbol and price. However, this seems less desirable.

**Comment by pixelzoom** [comment]
In order to fix this, I'll have to parse the cost pattern (`"${0}"`) identified in https://github.com/phetsims/unit-rates/issues/176#issue-212818202.  I'll need to extract the currency symbol, determine whether it goes before or after the number on the scale, and render it as a separate node.   In general, parsing a pattern string is something that should *never* be done.  Beyond verifying that the translation contains the `{0}` placeholder, Rosetta has no way to verify that the translation is syntactically correct (i.e. contains a currency symbol), so the sim will require logic to keep it from blowing up.  And in https://github.com/phetsims/phetcommon/issues/36, we will soon be changing the format of patterns, which will require whatever I do to be re-written. (The change will be transparent to sims that don't do evil things like this.)

**Comment by pixelzoom** [comment]
@ariel-phet suggested something like this...  

Have 2 strings in the string file:

```
  "currencySymbolLeft": {
    "value": "$"
  },
  "currencySymbolRight": {
    "value": ""
  },
```

If `currencySymbolRight` has a non-zero-length value, then use that currency symbol, put it on the right, and ignore `currencySymbolLeft`.   Otherwise use `currencySymbolLeft`, and put it on the left.  In pseudocode, the logic is:

```
if ( currencySymbolRight.length > 0 ) {
   costString = value + currencySymbolRight;
}
else {
   costString = currencySymbolLeft + value;
}
```

My concern with this approach is that embedding `if-then-else` logic like this in the string file is not obvious, and cannot be described to translators via Rosetta.  And Rosetta cannot force the translator to enter only one of these 2 strings.  So translators may enter their currency symbol in _both_ places, and either not test, or not understand what is happening.

**Comment by pixelzoom** [comment]
3/9/17 Skype call with @arouinfar and @ariel-phet:
Put currency symbol on the left for the scale.  Revisit if we get pushback from translators.

**Comment by pixelzoom** [comment]
@arouinfar please verify in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.70/unit-rates_en.html?showAnswers&randomEnabled=false

Here are a couple of screenshots showing the behavior with the `'€'` currency symbol, placed on the right in questions and answers.  Note that `'€'` still appears to the left of cost on the scale.

![screenshot_190](https://cloud.githubusercontent.com/assets/3046552/23814035/fa0bc520-059e-11e7-9af2-431d37a39e0b.png)

![screenshot_189](https://cloud.githubusercontent.com/assets/3046552/23814044/02169fa6-059f-11e7-919e-63187a1e5a7d.png)

**Comment by arouinfar** [comment]
Looks good to me! Thanks @pixelzoom.
