### ISSUE TITLE
Incomplete drags result in floating food

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#18]
1. Use finger A to grab some food
2. Use finger B to switch sim state (to a new food in the combo box, or to a new food in the scene select). Note switching screens does not cause an issue.
3. Switch back to step one's state

Here you can release finger A and the food will remain, or you can try to drag the food and it will refuse to move. Here's what it looks like after multiple runs of the procedure:

![img_0002](https://cloud.githubusercontent.com/assets/5863899/17069471/0738b76c-5014-11e6-82b8-cee242b63548.PNG)

Seen on Dalton (iPad Air 2, iOS 10 Beta 2). For phetsims/tasks#657.

Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html
Version: 1.0.0-dev.10 2016-07-21 17:04:55 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 10_0 like Mac OS X) AppleWebKit/602.1.40 (KHTML, like Gecko) Version/10.0 Mobile/14A5309d Safari/602.1
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 95.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"eaee6dbf","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"a2e4d843","branch":"master"}}

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/19c07842cc8818a6a8efe880b525a6515583a1dd

**Comment by schmitzware** [comment]
Fixed in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.12/

**Comment by phet-steele** [comment]
Still an issue in master.

**Comment by schmitzware** [comment]
For the developer,  this has something to do with the animation tweens (see. common/model/Movable.js) not completing when the item type changes. Not sure what the proper way to handle it is. One solution, would be to call the ShelfNode/ScaleNode "adjustItemPositions" either before or after an item type change. It's a bit of a sledgehammer-like approach though.

**Comment by pixelzoom** [comment]
No plans to address this in old implementation. Closing as "will not fix".
