### ISSUE TITLE
Clicking on a marker text area to edit becomes harder if the text area contains a value

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#182]
This is because the value string is not clickable. Users must resort to clicking on the outer part of the marker's text area. This is inconsistent with the questions panel, as the values entered there can still be clicked to allow editing. 

Can't click to edit (observe the state of my cursor change from screenshot to screenshot):
<img width="230" alt="ur1" src="https://cloud.githubusercontent.com/assets/5863899/23725235/04ea16d8-040d-11e7-874d-50dd5c410fd2.png">

Moving my cursor over to the side slightly and off the value string, can edit:
<img width="194" alt="ur2" src="https://cloud.githubusercontent.com/assets/5863899/23725247/12b98050-040d-11e7-80cb-8ef065ff8150.png">

Question panel always lets me click to edit:
<img width="282" alt="ur3" src="https://cloud.githubusercontent.com/assets/5863899/23725309/537aa95c-040d-11e7-9f5a-90361416eaf4.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#797.
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.68/unit-rates_en.html
Version: 1.0.0-dev.68 2017-03-07 05:58:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"e0b1c391","branch":"master"},"babel":{"sha":"88805de4","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"43ca9ac4","branch":"master"},"dot":{"sha":"16c2f26b","branch":"master"},"joist":{"sha":"695d3638","branch":"master"},"kite":{"sha":"f4c67cff","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"49b5cb0d","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"04879a99","branch":"master"},"scenery-phet":{"sha":"0bb107fe","branch":"master"},"sherpa":{"sha":"98566566","branch":"master"},"sun":{"sha":"dc8dcfbf","branch":"master"},"tandem":{"sha":"45e9ee17","branch":"master"},"twixt":{"sha":"2ffed75c","branch":"master"},"unit-rates":{"sha":"4712352f","branch":"master"}}

**Comment by pixelzoom** [comment]
@phet-steele Fixed in master, please verify.

**Comment by phet-steele** [comment]
👍
