### ISSUE TITLE
Numbers in questions accordion box typed as string.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#184]
The inputs for the question answers in the questions accordion box are numbers that are typed as strings.
I'm assuming this is specifically done for comparing correct answers with the inputted response. @pixelzoom 

Using stringTest=x produces the below image.
![image](https://cloud.githubusercontent.com/assets/13894380/23729819/425a47ea-0421-11e7-818d-2d450f1a6518.png)

Reference #159

**Comment by pixelzoom** [comment]
The red 'x' in the screenshot above is more than just a number.  It's a number that's formatted as currency using the pattern "${0}".  That pattern is what's being replaced with 'x' by stringTest.

Make sense?

**Comment by Denz1994** [comment]
Understood. Closing.
