### ISSUE TITLE
Dependencies.json breaks format for code review

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#185]
I noticed you recently added updated dependencies. It seems that other sims place their dependencies in the sim's repo at the same location.  Should the code review doc be updated to include dependencies.json in the repo structure section?

_Current documentation_
```
my-repo/
      assets/
      audio/
         license.json
      doc/
         model.md
         implementation-notes.md
      images/
         license.json
      js/
         (see section below)
      .gitignore
      my-repo_en.html
      my-repo-strings_en.json
      Gruntfile.js
      LICENSE
      package.json
      README.md
```

_Suggested change (with documentation that dependencies.json may be optional)_
```
my-repo/
      assets/
      audio/
         license.json
      doc/
         model.md
         implementation-notes.md
      images/
         license.json
      js/
         (see section below)
      dependencies.json
      .gitignore
      my-repo_en.html
      my-repo-strings_en.json
      Gruntfile.js
      LICENSE
      package.json
      README.md
```
@pixelzoom

**Comment by pixelzoom** [comment]
`dependencies.json` is indeed a file that will always be in that same location. It's not generated when you create the sim via "grunt create-sim". It's generated by the build process when you "grunt deploy-dev".  So it's not there until you've deployed at least 1 version.  But it should be there by the time a code review starts.   So, yes, please revise the code-review checklist (in phet-info) to include it.

**Comment by Denz1994** [comment]
Reference https://github.com/phetsims/phet-info/commit/1ce0a66a384cadb16d9a4cb1cc995f6d050048d4 for change in documentation.
