### ISSUE TITLE
change range and delta for hours spinners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#186]
Requested by @arouinfar:

For the hours spinners in Racing Lab screen:

• change the range to [0.5,10]
• change delta to 0.5

OK to show integer values as (e.g.) "7.0" in the spinner.

**Comment by pixelzoom** [comment]
@arouinfar dev version for your review:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.71/unit-rates_en.html?showAnswers&randomEnabled=false

Previously, the fastest rate was 100 miles/hour.  Since the minimum hours was changed to 0.5, the fastest rate is now twice as fast (100 miles / 0.5 hour = 200 miles/hour).   

This change has no affect on the relative speed that the car will move.  At 100 miles/hour, the car will move as fast as it did before.  1 second of sim time is still equivalent to 8 hours of race time.  If you want to experiment with changing this value, use the `raceTimeScale` query parameter (documentation below).

```js
    // Controls the animation speed of car races.
    // 1 second of sim type is equivalent to this many hours of race time.
    // Larger values make car animation run faster.
    raceTimeScale: {
      type: 'number',
      defaultValue: 8, // hours
      isValidValue: function( value ) { return value > 0; }
    },
```

**Comment by pixelzoom** [comment]
Since it sounded like this change request wasn't a "done deal", I also made it easy to undo this change, if desired.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Everything looks great, and the default animation speed still feels good. 

A question @pixelzoom -- please feel free to shoot this down if unreasonable. Non-integer values in the denominator are most useful when less than one. Would it be possible to piecewise define the step value? For values < 1, step in 0.25 increments. For values > 1, step in increments of 1. The denominator progression would then be 0.25, 0.5, 0.75, 1, 2, 3...

If this is not possible, then the updated spinner in dev.71 will still be a big improvement.

**Comment by pixelzoom** [comment]
It's possible. But then you're going to always see _two_ decimal places in the spinner.  I.e. the denominator progression would actually be 0.25, 0.50, 0.75, 1.00, 2.00, 3.00,...  Let me know if you want me to do that.

I should also say... While that progression may hit the "useful" values, I think that a progression like that is going to be mighty confusing to the user. Spinners typically have a consistent delta.

**Comment by pixelzoom** [comment]
I should also say... While that progression may hit the "useful" values, I think that a progression like that is going to be mighty confusing to the user.

**Comment by pixelzoom** [comment]
I should also say... While that progression may hit the "useful" values, I think that a progression like that is going to be mighty confusing to the user.    Spinners typically have a consistent delta.

**Comment by arouinfar** [comment]
@pixelzoom you make some excellent points.  For me, it comes down to whether or not the pedagogical benefit outweighs the quirks. Frankly, I'm not sure. @amanda-phet can you review and advise?

**Comment by amanda-phet** [comment]
I think that the current spinner is a great improvement over the original and would prefer not to have the two decimal places. My vote is to keep it as-is.

**Comment by arouinfar** [comment]
Thanks @amanda-phet! I'm also happy with the new spinner. 

There's no need for any further changes @pixelzoom. Closing.
