### ISSUE TITLE
make bags and items move up a couple of pixels on startDrag

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#187]
Requested by @arouinfar:
When you click on a bag or item, make it move straight up a few pixels, so that it's obvious that it has come off the shelf or scale.

**Comment by pixelzoom** [comment]
Bags and items now move up 5 pixels on pointer down.  I made it easy to change this value, and it can be changed independently for bags and items. 

@arouinfar for your review:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.71/unit-rates_en.html?showAnswers&randomEnabled=false

**Comment by arouinfar** [comment]
Looks great! Thanks @pixelzoom.
