### ISSUE TITLE
Query Parameters refactored into sim specific directories.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#190]
Following this bullet in the code review document:

> Are sim-specific query parameters (if any) identified and documented in one .js file in js/common/ or js/ (if there is no common/)? The .js file should be named {{REPO}}QueryParameters, for example ArithmeticQueryParameters for the aritmetic repository.

Currently, all of the query parameters are located in a common directory. Should screen specific query parameters be located in their own directory as suggested below:

**CommonQueryParameters:**
- ?log

**ShoppingQueryParameters**
- ?showCells
- ?showAnswers
- ?randomEnabled
- ?animationSpeed

**ShoppingLabQueryParameters**
- ?showCells
- ?randomEnabled
- ?animationSpeed

**RacingLabQueryParameters**
- ?raceTimeScale

**Comment by pixelzoom** [comment]
Nope. Read the review item again.  Query parameters are encapsulated in 1 file _per sim_, not per screen.  The idea is that team members and testers should have 1 place they need to consult.

**Comment by Denz1994** [comment]
Very true. Closing because this is handled correctly.

**Comment by Denz1994** [comment]
#159
