### ISSUE TITLE
Shopping Lab: default rates 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#191]
@pixelzoom as discussed, we'd like to change the default rates of carrots and purple candy on the Shopping Lab.

Default Rates:
Apples: $1/1 Apples
Carrots: $3/4 Carrots
Purple Candy: $3/2 pounds

**Comment by pixelzoom** [comment]
@arouinfar please verify in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.72/unit-rates_en.html

**Comment by arouinfar** [comment]
👍
