### ISSUE TITLE
Flag introduced as common code?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#192]
Would it be worth introducing the flags used in the racing screen as common code? 

![image](https://cloud.githubusercontent.com/assets/13894380/23876648/1c19f53a-0804-11e7-8b39-39eb6b076c7a.png)
![image](https://cloud.githubusercontent.com/assets/13894380/23877053/0f185154-0806-11e7-8dd0-03dd1765ea23.png)

**Comment by pixelzoom** [comment]
I think that would be premature. For something like this, we typically wait until a 2nd simulation needs it. Like you did with StopSignNode.

**Comment by Denz1994** [comment]
Sounds like a good workflow to maintain. Good input. Closing.

**Comment by Denz1994** [comment]
#159
