### ISSUE TITLE
Missing dispose function for derived property?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/unit-rates#194]
In `common\model\DoubleNumberLine.js` at the initializaion of `this.denominatorRangeProperty` (line 84) and `this.numeratorRangeProperty` on (line 106), it is documented that these properties need disposal.

I cannot find a corresponding disposal call for these properties. Please advise if I am missing something. Thank you.

**Comment by Denz1994** [comment]
#159

**Comment by pixelzoom** [comment]
`dispose` is not needed the for anything in the model, it exists for the lifetime of the sim.  The documentation was incorrect, fixed in the above commit.  Thanks for catching.

**Comment by Denz1994** [comment]
Understood. Thanks for the update. Closing.
