### ISSUE TITLE
create unit-rates-screenshot.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#195]
@arouinfar please send me a screenshot showing how you would like the sim's thumbnail and screenshot to appear on the PhET website.  You can use [1.0.0-dev.74](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.74/unit-rates_en.html?brand=phet). I'll handle creation of the final screenshot.

**Comment by arouinfar** [comment]
Let's go with something like this @pixelzoom 
<img width="1017" alt="screen shot 2017-04-03 at 9 50 44 am" src="https://cloud.githubusercontent.com/assets/8419308/24620559/0ba24112-1853-11e7-8e23-edbf70bd5e58.png">

**Comment by pixelzoom** [comment]
To create the above screenshot:
1. run [1.0.0-rc.1](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-rc.1/unit-rates_en.html)
2. go to Shopping screen
3. select Apples from combo box
4. drag left and center bags of Apples from shelf to center of scale

**Comment by pixelzoom** [comment]
I don't have a retina iPad, so can't create the screenshot.  @jessegreenberg volunteered to create it, thanks!

**Comment by pixelzoom** [comment]
@jessegreenberg see the steps in https://github.com/phetsims/unit-rates/issues/195#issuecomment-291208231 to configure the sim as @arouinfar specified in https://github.com/phetsims/unit-rates/issues/195#issuecomment-291203270. 

Please check the file in as `unit-rates/assets/unit-rates-screenshot.png`

**Comment by pixelzoom** [comment]
@phet-steele volunteered to do this, changing assignment.

**Comment by pixelzoom** [comment]
@phet-steele's commits:
https://github.com/phetsims/unit-rates/commit/928bcbe4a73554972ccfa9574692c81f13c3702f
https://github.com/phetsims/unit-rates/commit/e589f16b94a9f183b5c390f85575352ba2a4c85d

**Comment by pixelzoom** [comment]
@arouinfar See screenshot below. The apples on the scale are in a different position than your screenshot, but you said "something like", so I'm assuming that's OK.   If it is indeed OK, please close this issue.  Otherwise reassign to @phet-steele to change it.

![unit-rates-screenshot](https://cloud.githubusercontent.com/assets/3046552/24622238/7fc66af6-1861-11e7-8b3e-422c4b45b103.png)

**Comment by phet-steele** [comment]
> @arouinfar See screenshot below. The apples on the scale are in a different position than your screenshot, but you said "something like", so I'm assuming that's OK. If it is indeed OK, please close this issue. Otherwise reassign to @phet-steele to change it.

@arouinfar no need to check, I replaced the image with centered apples, it looks way better anyway.

The other commit I forgot to reference:
https://github.com/phetsims/unit-rates/commit/1d9ba8b93f611846521ceab03d3a7d335783404f

**Comment by pixelzoom** [comment]
I confirmed the change that @phet-steele checked in.

Note that he first deleted the old screenshot, then added the new screenshot, since he was using the GitHub interface to check in the file.  So history of the old screenshot (which likely won't be needed) will be a little non-obvious to locate.
