### ISSUE TITLE
Create sim primer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#197]
Tracking sim primer creation in this issue so that #1 can be closed.

Target Deadlines
- [ ] Script drafted by 4/14/17
- [ ] Script reviewed by 4/28/17
- [ ] First recording by 5/12/17
- [ ] Primer live by 6/1/17

**Comment by pixelzoom** [comment]
@arouinfar status of this?  Should it be labeled "priority:2-high"?

**Comment by ariel-phet** [comment]
Should not be labelled high priority, changing to medium

**Comment by arouinfar** [comment]
The Unit Rates primer has been published to the website. Progress was discussed in the #primers channel on Slack, but here are the milestones:

* 10/10/2017: AR and CW collaboratively scripted the Shopping and Shopping Lab screens
* 10/16/2017: AR and CW collaboratively scripted the Racing Lab screen
* 10/20/2017: CW uploaded draft recording for script verification
* 10/24/2017: AR reviewed draft, and suggested script tweaks
* 11/1/2017: CW uploaded an updated recording
* 11/8/2017: AR reviewed the recording, and approved it for production
* 11/13/2017: CW uploaded the primer to Vimeo and captioned it
* 11/13/2017: AR reviewed the captions, and suggested a few edits
* 11/28/2017: CW made the requested edits, and published the primer to the PhET site
