### ISSUE TITLE
Apply standard label set

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/unit-rates#2]
@mattpen can you apply the standard label set to this repo? 

Also, if this is something easy to show how to do, I am happy to the run the script myself in the future.

**Comment by ariel-phet** [comment]
Part of #1

**Comment by ariel-phet** [comment]
And please assign back to me when finished

**Comment by mattpen** [comment]
@ariel-phet - I've added the labels for unit-rates.

I added a [readme](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md) with instructions on how to run these scripts yourself if you want to, let me know if you have any questions about it.

**Comment by ariel-phet** [comment]
Thanks @mattpen - perhaps we can look together on Thursday to make sure I have what I need to do it myself.
