### ISSUE TITLE
Implement final Challenge prompts with design doc data

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#20]
There is still no decisions on candy rates & challenge questions so everything is still being randomly generated until that is finalized.

**Comment by arouinfar** [comment]
Self-assigning to finalize the candy prompts.

**Comment by arouinfar** [comment]
@schmitzware all prompts are in the design doc. Please make this your top priority, and publish a new dev version once you've updated the prompts.

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/8513bb99cffafc932b48d3de9f5176ab53cb24c7

Also, fixed a typo made by me in the carrot data

**Comment by pixelzoom** [comment]
@arouinfar Looks like this was addressed. Can you confirm?  Latest dev version is http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.21/unit-rates_en.html

**Comment by arouinfar** [comment]
@pixelzoom close but not quite.  I found a few values that needed to be updated -- two were outright typos (one in the code; one in the doc) and four that didn't conform to the guidelines described in the design doc and needed to changed. These are the red values from #117. Additionally, the fourth candy prompt needs to be inverted.

Edits to make:
- [ ] Invert fourth candy prompts to read "Candy for $[price]?" Where [price] is defined in the <a href="https://docs.google.com/document/d/1D4FBgMwvvQvo_jITN5a675KWMxseWiMZ-oN0rd7nG9A/edit#heading=h.wpl1y0tchzay">Unit Rates & Challenge Prompts</a> table in the design doc.
- [x] Apples, Set B, Prompt 3: change to 14 items
- [x] Lemons, Set D, Prompt 3: change to 11 items
- [x] Lemons, Set D, Prompt 4: change to $2.25 
- [x] Oranges, Set B, Prompt 3: change to 14 items
- [x] Pears, Set A, Prompt 7: change to $2.80
- [x] Purple Candy, Set B, Prompt 3: change to 3.2 lbs

**Comment by pixelzoom** [comment]
As I asked in #117... The design document has a table titled "Unit Rates & Challenge Prompts". What are the values shown in red?  E.g.:

![screenshot_30](https://cloud.githubusercontent.com/assets/3046552/19094413/42add21e-8a4d-11e6-814d-7e5ac6d95899.png)

Are these the "Edits to make" that are indicated in https://github.com/phetsims/unit-rates/issues/20#issuecomment-251588782?

**Comment by arouinfar** [comment]
> I found a few values that needed to be updated... These are the red values from #117.

Yes, @pixelzoom the red values from the aforementioned table are included in the "Edits to make" list.

**Comment by pixelzoom** [comment]
Done for both old and new implementations of Questions.

**Comment by pixelzoom** [comment]
@arouinfar please verify the changes in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.30/unit-rates_en.html?showNew&randomEnabled=false&showAnswers

With the `showNew` query parameter, the new implementation of Shopping (a work in progress) is added as a 4th screen. 

The other 2 query parameters are for the new Shopping screen only. `randomEnabled=false` turns off random selection of everything, so you can step through the questions in the same order that they appear in the design doc. `showAnswers` shows the answer for each question.

**Comment by arouinfar** [comment]
I was doing some issue cleanup, realized I hadn't verified this yet. Sorry for the delay @pixelzoom.

The questions now all match the Unit Rates & Questions table in the design doc, with the exception of the fourth candy prompts which are inverted. The fourth question should read "Candy for $[price]?"

**Comment by pixelzoom** [comment]
Hmmm... I thought that the Candy scene was different, and had all "Cost of ..." questions. So is this (see screenshot) a bug in the original Shopping screen? 

![screenshot_122](https://cloud.githubusercontent.com/assets/3046552/22086700/3624c1c2-dd97-11e6-8671-e2e599b7a8aa.png)

**Comment by arouinfar** [comment]
@pixelzoom the candy prompts were never meant to be different. There was a bug in the original implementation, and the change was requested in my first review https://github.com/phetsims/unit-rates/issues/20#issuecomment-251588782.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/unit-rates/issues/20#issuecomment-273628617, @arouinfar said:
> The fourth question should read "Candy for $[price]?"

... or is is supposed to read "pounds for $[price]?".   

For fruits and vegetables, we use the singular and plural item names ("Apple", "Apples") throughout the questions.  For candy, that is currently "pound" and "pounds".   Trying to make this different for candy is going to be a nontrivial problem. So I'm wondering if it's worth the effort, or whether "pounds for $16.75?" is sufficient?  

Also worth noting is that "Candy for $[price]?" doesn't tell the user what the units are for the value that they are entering.

**Comment by pixelzoom** [comment]
@arouinfar you can test drive "pounds for $[price]?" in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.34/unit-rates_en.html?showNew

**Comment by arouinfar** [comment]
@pixelzoom I think "pounds for $[price]?" sounds much, much better. However, I don't think we should use lowercase "pounds" at the beginning of the sentence. We could switch to "Pound" and "Pounds". However, switching to uppercase is problematic in other ways:
* "Pound" and "Pounds" will read as a proper noun in the questions (which it's not)
* It also looks odd to have lowercase "dollars" and uppercase "Pounds" next to one another in the double number line and rate panel on the Shopping Lab.

@pixelzoom will it take significant effort to add an additional string "Pounds" to be used only at the beginning of the 4th question on the candy scene? I know we have been very careful in minimizing the number of strings where possible, but I think we're going to want to keep "pound", "pounds", "lbs", and add "Pounds".

**Comment by pixelzoom** [comment]
@arouinfar asked:
> @pixelzoom will it take significant effort to add an additional string "Pounds" to be used only at the beginning of the 4th question on the candy scene?

Yes.  It will require adding Candy-specific code to several modules, complicating something that is currently relative simple. Imo, not worth the development cost or (inevitable) maintenance cost.   But your call.

**Comment by pixelzoom** [comment]
If consistence of capitalization is the issue, consider changing the other questions to "cost of 10 Apples?" and "unit rate?"

**Comment by pixelzoom** [comment]
If consistency of capitalization is the issue, consider changing the other questions to "cost of 10 Apples?" and "unit rate?"  None of these are complete sentences, so technically don't need to start with a capital letter.

**Comment by ariel-phet** [comment]
@pixelzoom I think we are a bit leary of getting pushback from teachers for having a sentence not capitalized at that level. Can you think of any alternatives that might serve the purpose but be simple to implement?

My druthers would certainly be consistency, and would prefer all non-caps to mixed

**Comment by pixelzoom** [comment]
> I think we are a bit leary of getting pushback from teachers for having a sentence not capitalized at that level

These are not sentences.

**Comment by ariel-phet** [comment]
@pixelzoom generally no, but with rising intonation such statements are considered sentences in general usage. "Feeling better today?" 😸

**Comment by pixelzoom** [comment]
OK, I will add "Pounds".  It will involve candy-specific code, like:

```js
if ( item instanceof Candy ) { 
  questionUnits = capitalPoundsString;
}
```

Two major problems I have with this:

(1) This type of code is the exact reason why I am having to rewrite this sim instead of simply fixing a few things. 

(2) This type of string key (`capitalPoundsString`) is something that I already spent hours eliminating (see https://github.com/phetsims/unit-rates/issues/57).

**Comment by arouinfar** [comment]
@pixelzoom the other alternative would be to change "pound" to "Pound", "pounds" to "Pounds" and dollars to "Dollars".

**Comment by arouinfar** [comment]
There would be some funkiness in the capitalization, but it would at least be consistent.

**Comment by pixelzoom** [comment]
"Pounds" is now capitalized when it appears as the first word of a question.  Implemented in above commit, which involved touching 3 modules to propagate yet-another candy-specific option.  There are now 9 such candy-specific code paths required in the new Shopping screen.

@arouinfar please verify in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.35/unit-rates_en.html?cm

**Comment by arouinfar** [comment]
👍
