### ISSUE TITLE
Objects from the shelf and the scale get stuck in mid air

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/unit-rates#21]
For phetsims/tasks#657
Test Device: Dalton
Operating System: iOS 10 Beta 2
Browser: Safari

Problem Description: When making quick and small drags on one object, the object will get stuck in mid air. It's most likely that the animation to return the object is getting interrupted. 

Steps to Reproduce: 
1. Drag an object from the shelf with quick and short motions
2. Place an object on the scale and observe the same result

https://drive.google.com/open?id=0B2k01kdMqJLDUkl5SFJrU2xmZUU

https://drive.google.com/open?id=0B2k01kdMqJLDU3l5S2pSZVNzS00

Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.10/unit-rates_en.html
Version: 1.0.0-dev.10 2016-07-21 17:04:55 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 10_0 like Mac OS X) AppleWebKit/602.1.40 (KHTML, like Gecko) Version/10.0 Mobile/14A5309d Safari/602.1
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 95.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"eaee6dbf","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"a2e4d843","branch":"master"}}

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/19c07842cc8818a6a8efe880b525a6515583a1dd

**Comment by schmitzware** [comment]
Fixed in:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.12/

**Comment by pixelzoom** [comment]
@alynne-phet or @arouinfar Can you please confirm? The latest dev version is http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.21/unit-rates_en.html.

**Comment by arouinfar** [comment]
@pixelzoom haven't been able to reproduce with a mouse. I'll test this on an iPad when I'm in the office tomorrow.

**Comment by arouinfar** [comment]
Looks good! Closing.
