### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/unit-rates#212]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Using the +/- buttons on the accordion boxes could be difficult

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56233104-99bcbc80-603f-11e9-8f38-e93a09e96c5c.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56233105-99bcbc80-603f-11e9-8d8b-af43106f503b.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56233106-99bcbc80-603f-11e9-98b6-840098a86982.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56233107-99bcbc80-603f-11e9-8520-3ece9eb8e327.png)

**Comment by pixelzoom** [comment]
> * Using the +/- buttons on the toolboxes could be difficult

I assume you mean accordion boxes?

**Comment by KatieWoe** [comment]
Yes

**Comment by pixelzoom** [comment]
> * Using the +/- buttons on the accordion boxes could be difficult

I don't see any good/quick options for improve this.  

The API for AccordionBox only supports symmetric dilation of the pointer areas.  I.e., pointer areas expand the same amount above/below and left/right of the button.  

AccordionBox's button is `ExpandCollapseButton`, whose superclass is sun's `RectangularButtonView`.  So if we want to support shifting pointer areas, that will require adding the following options to `RectangularButtonView`: 

```js
touchAreaXShift: 0,
touchAreaYShift: 0,
mouseAreaXShift: 0,
mouseAreaYShift: 0,
```

My question is whether the need here is great enough to justify the amount of work involved.

**Comment by KatieWoe** [comment]
I'm not sure it is.  Up to @kathy-phet and @amanda-phet

**Comment by pixelzoom** [comment]
Actually, this doesn't look that difficult.  In RectangularButtonView, add the options shown above. Then change this:

```js
    // set pointer areas
    this.touchArea = button.localBounds.dilatedXY( options.touchAreaXDilation, options.touchAreaYDilation );
    this.mouseArea = button.localBounds.dilatedXY( options.mouseAreaXDilation, options.mouseAreaYDilation );
```

to this:

```js
    // set pointer areas
    this.touchArea = button.localBounds.dilatedXY( options.touchAreaXDilation, options.touchAreaYDilation ).shifted( options.touchAreaXShift,  options.touchAreaYShift );
    this.mouseArea = button.localBounds.dilatedXY( options.mouseAreaXDilation, options.mouseAreaYDilation ).shifted( options.mouseAreaXShift,  options.mouseAreaYShift );
```

**Comment by pixelzoom** [comment]
A better API for `RectangularButtonView` might be:

```js
touchAreaXAlign: 'center', // left, right, center
touchAreaYAlign: 'center', // top, bottom, center
```

This doesn't support arbitrary shifting, but makes it easier to specify the typical cases.

**Comment by pixelzoom** [comment]
I've created https://github.com/phetsims/sun/issues/500 to track the general enhancement that would be required in RectangularButtonView.  

@arouinfar Let me know whether you think we need to address this issue, because it will affect the priority of the more general issue.

**Comment by arouinfar** [comment]
The solution you've proposed seems pretty straightforward @pixelzoom. Generally, I think it would be a worthy investment to add support for asymmetric dilation of touch areas to `RectangularButtonView`, as the `ExpandCollapseButton`'s are a bit hard to use on my phone.

The reality is that many teachers do have students pull up sims on their phones. Given that we have iOS and Android apps, it seems like a bit of a cop-out out not to optimize touch areas. However, it is entirely up to @kathy-phet and @ariel-phet to decide how much developer time we should be investing into common code changes.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar I agree worth the time, especially since it seems like a generally good improvement to the flexibility of `RectangularButtonView`

**Comment by pixelzoom** [comment]
Blocked by phetsims/sun#500.

**Comment by pixelzoom** [comment]
Touch areas for all expand/collapse buttons in this sim are now shifted up, see sample screenshot below. @arouinfar could you please review?

<img width="909" alt="screenshot_1175" src="https://user-images.githubusercontent.com/3046552/57097327-b52cf600-6cd4-11e9-8579-851d210723d2.png">

**Comment by arouinfar** [comment]
👍
