### ISSUE TITLE
Unused option ValuePanel.titleMaxWidth

### ISSUE THREAD

**Issue by zepumph** [phetsims/unit-rates#213]
While working on https://github.com/phetsims/gravity-force-lab/issues/165 I noticed, via a global search of `titleMaxWidth`, that this option doesn't appear to be used. @pixelzoom sorry if I just don't understand, but over to you to fix or clarify.

**Comment by pixelzoom** [comment]
I inherited this sim from another developer, and commit history for `ValuePanel` indicates that it was "a rewrite of scale and timer display".  So I'm guessing that `titleMaxWidth` is a vestigial option from some code that I inherited and rewrote.    The title's `maxWidth` appears to be properly computed, and I see no `titleMaxWidth` option in the superclass (Panel), so I'll go ahead and remove it.
