### ISSUE TITLE
Color code number line/challenge prompt

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#22]
Make the challenge prompt lines a different color. 

Keep challenge prompt titles black, answers color code. 

Unit rate [green] and other challenges [blue]. 

Scale state stays on numberline (black).

**Comment by arouinfar** [comment]
@schmitzware here's a mockup of the color-coordinated challenge prompts and double number line. 

Green: 00a551
Blue: 0040ff

![image](https://cloud.githubusercontent.com/assets/8419308/17205444/577c0f96-5468-11e6-89db-f7835fd4dbd3.png)

![image](https://cloud.githubusercontent.com/assets/8419308/17204430/b97f5a5a-5462-11e6-97d1-39491ff593fc.png)
(Please disregard the scaling of the double number line -- the mockup hasn't been updated to reflect 16 tick marks.)

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/1a41b4b2fc41cc81796770be6a45857ef6149d0a

**Comment by arouinfar** [comment]
👍
