### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#222]
Currently at ~5% completed.

**Comment by pixelzoom** [comment]
This is now ~85% completed.  See TODO items in the code (with this issue number) for remaining work.  Most of the remaining work is in ShoppingQuestionFactory.ts, where question are dynamically generated for the Shopping screen.

**Comment by pixelzoom** [comment]
Support for dynamic locale is completed.  This requires review before the sim is published from main.

**Comment by pixelzoom** [comment]
Please verify dynamic locale/layout support in https://github.com/phetsims/qa/issues/1111.   Close if it looks OK.

**Comment by KatieWoe** [comment]
Things seem to be looking good. Will reopen if issues come up.
