### ISSUE TITLE
Update credits for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#225]
For #224. Current credits are shown below.

<img width="626" alt="screenshot_3408" src="https://github.com/phetsims/unit-rates/assets/3046552/485f0578-a4b3-4b9b-91ae-70ac67fd0035">

**Comment by pixelzoom** [comment]
Please specify changes to the QA credits for https://github.com/phetsims/qa/issues/1111.

**Comment by KatieWoe** [comment]
Nancy Salpepi, Kathryn Woessner, Ashton Morris, and Matthew Moore can be added for QA

**Comment by pixelzoom** [comment]
Please specify changes to the QA credits for https://github.com/phetsims/qa/issues/1151 (1.1.0-rc.1)

**Comment by Nancy-Salpepi** [comment]
No changes here

**Comment by pixelzoom** [comment]
Please specify changes to the QA credits for https://github.com/phetsims/qa/issues/1158 (1.1.0-rc.2)

**Comment by KatieWoe** [comment]
No new QA credits.

**Comment by pixelzoom** [comment]
QA process is completed, and so are the credits. Publishing 1.1.0.
