### ISSUE TITLE
Replace decorator pattern used in DoubleNumberLineAccordionBox

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/unit-rates#227]
From https://github.com/phetsims/sun/issues/860, components with "content" cannot be decorated with other Nodes and this case was found.

https://github.com/phetsims/unit-rates/blob/24ae5e0661183c863d156871338b31706bb95fdb/js/common/view/DoubleNumberLineAccordionBox.ts#L145-L148

A potential way to replace this is in the following commit, @pixelzoom can you please review and change if there is a better way for this sim?

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg, that's a nice improvement.  Closing.
