### ISSUE TITLE
Eraser behavior is different than in published

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/unit-rates#228]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1111, on all three screens pressing the eraser button removes one marker at a time, while in published it erases all of the markers. 

**Steps to reproduce**
1. On the Shopping Screen, add 5 apples to the scale
2. Remove 1 apple
3. Remove another apple
4. Press erase button
5. Follow the same steps in published

**Visuals**

https://github.com/user-attachments/assets/7ee961df-2ddc-4555-96e2-6ed09b4c8611

**Comment by pixelzoom** [comment]
Reproduced in main.

The behavior is different on all 3 screens. I'm guessing that this is a regression that was introduced during conversion to TypeScript.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  @Nancy-Salpepi please verify in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good on main! Closing.
