### ISSUE TITLE
Erase question answers after they are no longer there

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/unit-rates#230]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1111, but it does happen in the published sim.
On the Shopping screen if you solve a question, the answer shows up on the numberline and isn't erased by the erase button. This is correct. However, if you refresh the questions, the erase button should erase those entries, aside from the unit price. This does not work. Those question answers stay on the number line until you press reset all.
From @arouinfar on Slack:
> When you refreshed the challenges, the only line that should have been left is the unit rate. Values represented by the current state of the scale, and correctly answered challenges should not be cleared from the number line.

**Steps to reproduce**
1. Go to the Shopping screen
2. Answer one of the questions
3. Make sure the scale doesn't have the same number of items as the question for the next parts.
4. Press the erase button on the number line, the answer stays. This is correct.
5. Press the refresh button on the Questions box
6. Press the erase button on the number lin, the answer stays. This is incorrect.

**Visuals**
![eraseoldnumberline](https://github.com/user-attachments/assets/ddefa1f6-c9b3-466d-9e69-8196a9e112c1)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Unit Rates‬
URL: https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.11/phet/unit-rates_all_phet.html
Version: 1.1.0-dev.11 2024-10-01 00:19:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Reproduced in main and the published version.

**Comment by KatieWoe** [comment]
I also saw it in published.

**Comment by pixelzoom** [comment]
@KatieWoe ready for review. Close if OK.

The new behavior is:
* Pressing the refresh button in the Questions accordion box removes markers for any questions that had been answered correctly, except for the Unit Rate question.
* Pressing the erase button in the Double Number Line accordion box does not remove markers for any correctly-answered questions that appear in the Questions accordion box.

**Comment by KatieWoe** [comment]
The number line issue seems largely fixed, but I've noticed another oddity. When refreshing the Question box, if it comes up with a challenge you've already solved, it will appear solved in the Questions box. But no marker appears on the number line. For example if you solve a Cost of 10 items question, then refresh the Questions box a few times, if/when the 10 items question comes up again it will already have the solution, and nothing will be on the number line.
Note: The answer appearing again when the question comes back is in published, so may be the intended behavior. @arouinfar is it intended or a bug?

**Comment by pixelzoom** [comment]
Reproduced in main.  

@arouinfar what is the desired behavior when a previously-answered question comes up again?  The options are:

(1) When the refresh button is pressed in the Questions accordion box, mark all questions (except the Unit Rate question) as unsolved and clear their answers. The next time the same set of questions is loaded, they will show no answers, and the user can answer them again. This requires no changes to how markers are managed. 

(2) Retain the answers to all questions that were previously answered. When a previously-answered question comes up again, show its answer in the Questions accordion box and add markers for answered questions to the number line.  This will require changes to how markers are managed. 

(1) feels like the more useful behavior to me.

**Comment by pixelzoom** [comment]
Below is a patch for option (1) that I described above.  It involves adding 1 line of code. Option (2) would be significantly more complicated.

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] clear markers for non-unit-rate questions when refreshing the question set, https://github.com/phetsims/unit-rates/issues/230
---
Index: js/shopping/model/ShoppingScene.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/shopping/model/ShoppingScene.ts b/js/shopping/model/ShoppingScene.ts
--- a/js/shopping/model/ShoppingScene.ts	(revision aba0fcefd809704e9307f9f1330443d8eb82c994)
+++ b/js/shopping/model/ShoppingScene.ts	(date 1728070776740)
@@ -419,6 +419,9 @@
       }
     } );
 
+    // Reset the previous questions so that they are all unsolved.
+    this.questionSetProperty.value.forEach( question => question.reset() );
+
     // adjust the index to point to the next question set
     if ( this.questionSetsIndexProperty.value < this.questionSets.length - 1 ) {
       this.questionSetsIndexProperty.value = this.questionSetsIndexProperty.value + 1;
```

</details>

**Comment by pixelzoom** [comment]
I also noticed something odd for the questions related to Pears.  There are 4 sets of questions, shown below.  The first "Cost of" questions is 10 in two cases, and 15 in the other two cases.  Why are we using the same values in more than one question?  

Cost of 10 Pears?
Cost of 6 Pears?
Pears for $2.80?

Cost of 10 Pears?
Cost of 14 Pears?
Pears for $4.80?

Cost of 15 Pears?
Cost of 11 Pears?
Pears for $5.20?

Cost of 15 Pears?
Cost of 4 Pears?
Pears for $3.20?

**Comment by pixelzoom** [comment]
Discussed with @arouinfar, and we'll do option (1).

**Comment by pixelzoom** [comment]
Questions are now reset (cleared) when the the refresh button is pressed in the Questions accordion box. So when you cycle back to a set of questions, you will not see answers that you gave previously.  The "Unit Rate" question is not affected.

@KatieWoe please review. Close if OK.

**Comment by KatieWoe** [comment]
This seems fixed on main
