### ISSUE TITLE
Grab Hand appears when clicking on keypad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/unit-rates#234]
**Test device**
MacBook Air M1 chip and Dell

**Operating System**
15.0 + Win10

**Browser**
Safari 18.0 + Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1151, if I click on the gray part of any calculator, the pointer becomes a hand making it seem like I can then move the calculator, which I can't. The hand doesn't appear when hovering over the gray part of calculator, it only appears after clicking. 

This was introduced between 1.0.32 and 1.1.0-dev.10.

**Steps to reproduce**
1. On any screen, press the Edit (?) button to make the calculator appear
2. Click on a gray part of the the calucator

**Visuals**

https://github.com/user-attachments/assets/b75bb696-4910-47c3-93cd-cdad98daaa8b

**Comment by pixelzoom** [comment]
Reproduced in main and 1.1 branches.

@Nancy-Salpepi said:
> This was introduced between 1.0.32 and 1.1.0-dev.10.

Thanks for trying to determine when it was introduced! But those version are from different branches, so comparing them does not tell us anything about when something changed.

Comparing 1.1 versions... This problem was introduced between 1.1.0-dev.2 (10/11/2017) and 1.1.0-dev.3 (5/22/2023).  That's unfortunately a very long period, with many commits in between.  So this will be difficult to track down by bisecting commits.

**Comment by pixelzoom** [comment]
Inspecting commits for KeypadPanel.ts seems more promising.  There are only ~12 commits between 10/11/2017 and 5/22/2023.   And I'll bet it's https://github.com/phetsims/unit-rates/commit/a7a21e52dd85fb03e45433bf775bd848cbcec998, "replace NumberKeypad with Keypad".

**Comment by pixelzoom** [comment]
This problem was introduced by a scenery change in the behavior of PressListener. See https://github.com/phetsims/scenery/issues/1013.  It was fixed in the above commit.

@Nancy-Salpepi please review. If it looks OK, change the label to fixed-awaiting-deploy for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
Looks fixed!

**Comment by pixelzoom** [comment]
I realized that I had not cherry-picked the fix to the 1.1 branch. So that was done in https://github.com/phetsims/unit-rates/commit/cb83d7870e9d427f1a33c214bb07376729612093.

**Comment by Nancy-Salpepi** [comment]
I changed the title for you...😊

**Comment by pixelzoom** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/1158 for 1.1.0-rc.2.  It is sufficent to verify on 1 platform. Close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2
