### ISSUE TITLE
Cannot take items off the scale and place them directly on the shelf

### ISSUE THREAD

**Issue by phet-steele** [phetsims/unit-rates#26]
From the changes in #11, an object returned directly to the shelf (released in the white area) will visibly remain on the shelf while the sim still treats it as being on the scale. See how the value on the scale never changes, and when I add something to the scale the other objects "correct" themselves:

![ur02](https://cloud.githubusercontent.com/assets/5863899/17299681/91d8bd9e-57cc-11e6-9f64-73f84e6ce008.gif)

Seen on OSX 10.11.6 Chrome, iOS 10 Beta 2, and Samsung Galaxy S5 Android 6.0.1 (because why not).
Troubleshooting information:
Name: ‪Unit Rates‬
URL: http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.12/unit-rates_en.html
Version: 1.0.0-dev.12 2016-07-27 19:05:07 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"8c922dab","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"183dcea4","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"ab7223ad","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"acf94bc0","branch":"master"},"sherpa":{"sha":"0f4d5f25","branch":"master"},"sun":{"sha":"c7b647dd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"unit-rates":{"sha":"cff831bb","branch":"master"}}

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/6c05e604cfff72fd511a97f6bbe89e866a57bcb7

**Comment by phet-steele** [comment]
Fixed, closing.
