### ISSUE TITLE
assert( true )

### ISSUE THREAD

**Issue by andrewadare** [phetsims/unit-rates#31]
Are these correct? I would think you want assert(false) inside these conditions:

Searching 38 files for "assert( true"

/Users/adare/phetsims/unit-rates/js/common/view/EditNumberDisplayNode.js:
  106      }
  107      else {
  108:       assert && assert( true, 'invalid buttonPosition for EditNumberDisplayNode' );
  109      }
  110  

/Users/adare/phetsims/unit-rates/js/shopping/model/Challenges.js:
  308            case ItemData.BLUE_CANDY.type:
  309            default:
  310:             assert && assert( true, 'no name available for item type' );
  311          }
  312  

/Users/adare/phetsims/unit-rates/js/shopping/view/CandyContainerNode.js:
  143              break;
  144            default:
  145:             assert && assert( true, 'Candy container is populating non-candy types' );
  146        }
  147        this.candyTopNode.fill  = itemColor;

/Users/adare/phetsims/unit-rates/js/shopping/view/ItemComboBox.js:
  103          break;
  104        default:
  105:         assert && assert( true, 'Combo box using unrecognized type' );
  106      }
  107  
  ...
  133            break;
  134        default:
  135:         assert && assert( true, 'Combo box using unrecognized scene' );
  136        }
  137  

/Users/adare/phetsims/unit-rates/js/shopping/view/ItemNodeFactory.js:
   84              break;
   85            default:
   86:             assert && assert( true, 'Node factory cannot create item of unrecognized type' );
   87          }
   88  

/Users/adare/phetsims/unit-rates/js/shopping/view/NumberLineNode.js:
  134              break;
  135            default:
  136:             assert && assert( true, 'Number line using unrecognized type' );
  137          }
  138  

/Users/adare/phetsims/unit-rates/js/shopping/view/ShoppingScreenView.js:
  228            break;
  229          default:
  230:           assert && assert( true, 'Unrecognized scene' );
  231        }
  232      },
  ...
  257            break;
  258          default:
  259:           assert && assert( true, 'Unrecognized scene' );
  260        }
  261  

9 matches across 7 files

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/22446793a68ae9efd1930932ec8077b7cdf768be
great catch - thanks!
