### ISSUE TITLE
Chained methods with a trailing dot?

### ISSUE THREAD

**Issue by andrewadare** [phetsims/unit-rates#33]
`setPosition` in Item.js contains this chained method call:

``` js
var animationTween = new TWEEN.Tween( position ).
          to( {
            x: x,
            y: y
          }, 1000 ).
          easing( TWEEN.Easing.Cubic.Out ).
          onUpdate( function() {
            self.setPosition( position.x, position.y, false );
          } ).
          onComplete( function() {
          } );
```

I'm not sure about this (hence the question tag), but I think it's more idiomatic to start new methods in the chain with the dot. Didn't see anything in the dev guide on this, but the examples in the [online scenery docs](http://phetsims.github.io/scenery/doc/) follow that pattern.

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/ff520e91870a0bf2074afff3a02de7bb46d2eb23
