### ISSUE TITLE
Stacked fruit sometimes does not fall

### ISSUE THREAD

**Issue by schmitzware** [phetsims/unit-rates#36]
Occasionally when you remove a bottom fruit from the scale the fruit item stacked on top of it fails to slide down to take a bottom position.

This seems random, I haven't been able to reproduce it consistently.

**Comment by schmitzware** [comment]
For the next developer, best place to start is in common/shopping/view/ScaleNode.js, in the function 'adjustItemPositions'. This does the layout/stacking and initiates the moving of stacked items to the bottom of the shelf. The positioning/animating code is down in common/model/Movable.js. This uses Tween which may be the culprit. I just haven't had a chance to look deeper. Also, worth mentioning is the matching node, found in common/view/MovableNode.js which handles all the dragging. Could be something funky there as well.

**Comment by pixelzoom** [comment]
No plans to address this in old implementation. Closing as "will not fix".
