### ISSUE TITLE
Dismiss number pad after submission

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#37]
When manually adding lines to the double number line, I often catch myself overwriting the first number entered because I expect the focus to automatically move to the 2nd box. For example, I'll manually add a line at 6 apples, and then I'll immediately enter a 3 (meant to be $3.00) without clicking on the appropriate edit button, and the line shifts to to 3 apples.  If I expect this behavior (despite knowing better), other users may also expect this. 

Rather than changing the behavior of the focus (which could get pretty messy), I think it would be better to dismiss the number pad after clicking "submit" to avoid cueing this expectation.

**Comment by schmitzware** [comment]
Good idea, Amy. I just added this.
https://github.com/phetsims/unit-rates/commit/eaa4733210754b5c3a01079442e2ca574e57c535

**Comment by arouinfar** [comment]
Looks great! Thanks @schmitzware
