### ISSUE TITLE
Minor tick marks broken

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#38]
In the latest dev, minor tick marks corresponding to a fractional number of items are no longer inset and gray.

Compare dev.15 (top) and dev.14 (bottom). The desired behavior is dev.14.
![image](https://cloud.githubusercontent.com/assets/8419308/17783578/e4494ab4-6535-11e6-89bb-9a5c8339e9a5.png)
![image](https://cloud.githubusercontent.com/assets/8419308/17783599/facaed88-6535-11e6-88a4-42c7a88d1a2d.png)

**Comment by schmitzware** [comment]
Fixed rounding error when getting the precision of a float. (i.e. 1.0000003)
https://github.com/phetsims/unit-rates/commit/fb194170c32ed06335e7ce5d9222843559d1c871

**Comment by arouinfar** [comment]
👍
