### ISSUE TITLE
bad type expressions for @param

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#41]
ShoppingScreenView line 131:

``` js
     * @param {Property}.<SceneMode> sceneMode - indicates the scene type
     * @param {Property}.<ItemData> fruitItemData - the item data for the selected fruit item
     * @param {Property}.<ItemData> produceItemData - the item data for the selected produce item
     * @param {Property}.<ItemData> candyItemData - the item data for the selected candy item
```

IntelliJ IDEA is flagging all of the above type expressions as invalid.  The correct general format is `{Property.<type>}`, e.g. `{Property.<SceneMode>}`.

I did not check to see if this is a problem in other source files.

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/c42b171db68c1563dd4a4d862704ddd883f15ba2

**Comment by pixelzoom** [comment]
👍 Closing.
