### ISSUE TITLE
bad visibility annotation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#42]
ShoppingScreenView line 142:

``` js
 this.removeAllItems();
```

IntelliJ IDEA is flagging this as "Private member is not accessible". 

You can fix this by changing the visibility annotation for `URShoppingScreenView.removeAllItems` from `@private` to `@protected`.

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/c42b171db68c1563dd4a4d862704ddd883f15ba2

**Comment by pixelzoom** [comment]
👍 Closing.
