### ISSUE TITLE
open keypad if the user click on an editable field

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/unit-rates#45]
Consider making a click on the box of an unanswered challenge equivalent to hitting the official edit button. And either behavior pulls up the numberpad entry for that challenge. In playing with the sim, I was inclined to hit the empty box with my mouse. 

Amy R - what do you think?

**Comment by arouinfar** [comment]
Great idea @kathy-phet! I agree that this would be a nice change to make. Assigning to @schmitzware.

**Comment by amanda-phet** [comment]
Just throwing this out there- the reason we don't have this behavior is because a lot of HTML5 sims have readouts in white rectangles that you _can not_ edit (while in java sims you _can_ click the rectangle to edit), so it would be more consistent in this sim to have the same behavior. If users can click on a rectangle in this sim they might try to do it in other sims and get frustrated.

**Comment by kathy-phet** [comment]
My suggestion was based on what my natural action was, so I think it will help will flow. I was cuing off of the edit button for sure, so I think that it won't necessarily create expectations when an edit button is not there. I think the edit button could signify that you can enter something into this box and not confuse users when there is no edit button available. 

I think the ease of use of this sim would increase quite a bit, so I would favor expanding the touch area to include the answer box. Basically, making it so you can touch anywhere in the vacinity of the answer and you will get the pad.

**Comment by arouinfar** [comment]
While I understand your point @amanda-phet, I tend to agree more with what @kathy-phet has said. However, I think this issue could wait until after the first round of interviews. If we find students attempt to click/touch the boxes to edit them, then I think we should support that interaction. Otherwise, we may not need to support clicking/touching the box to edit, which would preserve the behavior has @amanda-phet has described.

**Comment by amanda-phet** [comment]
I wasn't disagreeing, just sharing the discussion that led to having an edit button at all. I don't think we need to wait for interviews, but if we think the larger touch area will increase usability (I agree that it will) we should consider doing the same in other sims that use edit buttons (Make-a-ten, AMM, Projectile Motion).

**Comment by arouinfar** [comment]
Ah, got it @amanda-phet. I agree that we should keep the behavior consistent across sims with edit buttons. I'll remove the on-hold tag, but will still look out for this in interviews.

Ian has also reported that clicking the textboxes would be a useful change.

> I think many students (and teachers) instinctively click on the textboxes in order to type in them. Eventually, they figure out that they need to click on the yellow squares instead, but this is a bit unusual and counterintuitive. Can the sim be modified so that one can click on a textbox in order to type in that textbox?

**Comment by schmitzware** [comment]
The easiest way to handle this is as Kathy said - "expanding the touch area to include the answer box"

I'll just throw my 0.02 in - I would pick one way to edit for all sims and stick with it. Having said that,  seems like most other applications (mobile, web, desktop) just use 'clickable text boxes' to set focus and make edits.

**Comment by arouinfar** [comment]
> The easiest way to handle this is as Kathy said - "expanding the touch area to include the answer box"

Sounds good @schmitzware. The change should also apply to click areas as well.

>  I would pick one way to edit for all sims and stick with it. 

In general, that's the goal. However, we often have readouts in boxes that are not editable with a keypad, like these:
![image](https://cloud.githubusercontent.com/assets/8419308/18320646/f678c89c-74e7-11e6-85bb-d14d19592d4a.png)

We want to avoid training students to think that clicking on these sorts of readouts will open the keypad. While the edit button is technically redundant, it serves as a visual cue that the readout supports keypad entry and is somehow different from other readouts (like the one above).

**Comment by schmitzware** [comment]
For the next developer, as mentioned above, the easiest way to handle this is to extend the touch area from the edit buttons to cover the text box.  This can be done in common/view/EditNumberDisplayNode.js

A EditNumberDisplayNode is just a button and a NumberDisplay.

**Comment by arouinfar** [comment]
During interviews, students definitely tried clicking on the boxes to pull up the keypad. We should extend the click and touch areas of the edit buttons to include the corresponding boxes.

**Comment by pixelzoom** [comment]
This is implemented in the new ShoppingQuestionNode.  Closing.
