### ISSUE TITLE
Unit Rate Challenge in Candy doesn't populate Double Number Line

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/unit-rates#46]
When I answer the Unit Rate challenge on the Candy scene, it is not putting the green line on the double number line for some reason. It does on the other scenes. If I refresh the challenges, it does at it. 

Please check out this behavior.

**Comment by schmitzware** [comment]
f98ddcb

**Comment by schmitzware** [comment]
https://github.com/phetsims/unit-rates/commit/f98ddcb9c2f2c877829a0bec586aec4498f65a74

**Comment by pixelzoom** [comment]
This is assigned to @kathy-phet for review, but there's no dev version indicated for review.  I'll label as "ready for review".

**Comment by pixelzoom** [comment]
@kathy-phet Since this was fixed 26 days ago, you should be able to verify in [1.0.0-dev.20](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.20/unit-rates_en.html).  If it looks good, please close this issue. Otherwise report what is still wrong.

**Comment by pixelzoom** [comment]
@arouinfar Can you please verify this?

**Comment by arouinfar** [comment]
This appears to have been addressed @pixelzoom. However, challenge prompts corresponding to off-scale values should not be added to the double number line (eg. 22 carrots). I think this is a separate issue, so I'll go ahead and close this one and open a new one.
