### ISSUE TITLE
Location of objects on the shelf not saved in state

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/unit-rates#47]
Consider whether location of objects on the shelf should be saved. Right now, the objects can shift from when you leave a particular type of fruit and then return back to it later. Seems like a bug, but not particularly high priority.

**Comment by arouinfar** [comment]
Good idea @kathy-phet. I agree that this is not a particularly high priority bug to fix, but it should be addressed before publication. Assigning to @schmitzware.

**Comment by schmitzware** [comment]
For the next developer, this is not implemented in any way as it wasn't mentioned in the design doc. Currently items on the shelf/scale will populated across the of the node, then stacked on top on one another. This is done in the 'adjustItemPositions' function in both the ShelfNode & ScaleNode. This gets called from 'populate' which in turn gets called when the item type (i.e. apples, carrots, etc..) changes.  One should start around there to implement this.

**Comment by pixelzoom** [comment]
The new implementation will fully save state of the shelf and scale.  No plans to fix in the old implementation. Closing this issues as "will not fix".
