### ISSUE TITLE
Create Screen/Navbar Icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/unit-rates#49]
We need icons! Self-assigning.

**Comment by arouinfar** [comment]
I've created some tentative icons. I chose purple candy for the Shopping screen because it feels the most fun/inviting. For the Shopping Lab, the only options would be apples, carrots, or purple candy. To avoid two like (or like-colored) icons, I chose carrots. For the home screen icon, I think the the spinner would look odd if the units weren't somehow displayed. We want to avoid strings (dollars, carrots) in the icon so I went with a more symbolic representation.  While the dollar symbol will be translatable in the sim, I don't think it could be translatable in the screen icon. However, a dollar symbol is universally understood to be currency, so I don't think it would be a huge problem if the sim uses ¥, but the home screen icon shows a $. I didn't include a spinner in the Racing Lab icon, because I couldn't think of a reasonable way to symbolically display miles or hours.

<img width="1024" alt="screen shot 2016-09-23 at 5 38 59 pm" src="https://cloud.githubusercontent.com/assets/8419308/18804164/a77e1d4e-81b4-11e6-91a7-096ea4458e27.png">

Here are the icons in context. 
<img width="1024" alt="screen shot 2016-09-23 at 5 37 18 pm" src="https://cloud.githubusercontent.com/assets/8419308/18804135/7107fc9e-81b4-11e6-8ee5-97db5937c178.png">

We could simplify the icons for the navbar. For the Shopping Lab I made the spinner larger and removed the labels. We could also remove the scale from the Shopping icon. 
<img width="1024" alt="screen shot 2016-09-23 at 6 05 18 pm" src="https://cloud.githubusercontent.com/assets/8419308/18804459/76dbc57a-81b8-11e6-8ec5-66349f7635a4.png">
<img width="1024" alt="screen shot 2016-09-23 at 6 03 57 pm" src="https://cloud.githubusercontent.com/assets/8419308/18804460/7982d336-81b8-11e6-86bb-41ec2fdf48e4.png">

**Comment by arouinfar** [comment]
@ariel-phet can you take a look at these when you have a moment?

**Comment by ariel-phet** [comment]
@arouinfar here are my thoughts
1. Shopping screen just go with the bag of purple candy
2. Perhaps for the lab just have some individual items on the scale (I think not having a bag for this screen would be good to differentiate.) A few carrots on the scale or shelf?
3. Racing Lab looks great

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet! In response to your comments
1. Agreed.
2. Apple bags open; carrots do not. If we go with individual items on the scale or shelf, it should be apples. I'll mock up a few options.
3. Great!

**Comment by pixelzoom** [comment]
@arouinfar Are these icons checked into GitHub? What is the filename or filenames?

**Comment by arouinfar** [comment]
@pixelzoom the icons are still going through the design process. I'll send them to you once they're ready to be checked in.

**Comment by arouinfar** [comment]
@ariel-phet what about these? I swapped carrots for apples, since apple bags open.

<img width="839" alt="screen shot 2016-10-04 at 6 05 23 pm" src="https://cloud.githubusercontent.com/assets/8419308/19096870/4e83b468-8a5d-11e6-95da-f559a0e88d2a.png">

<img width="1024" alt="screen shot 2016-10-04 at 6 06 18 pm" src="https://cloud.githubusercontent.com/assets/8419308/19096871/4e96bb6c-8a5d-11e6-8ced-39f2ae7027ec.png">

**Comment by pixelzoom** [comment]
These look good. My only nits:

• There's little too much 'red' with the apples and car. Perhaps use the blue car?
• The car needs a number (see #108) on the home screen icon. If you want to leave it out on the navigation bar icon, we'll need separate artwork. (Navigation bar icons default to scaled down versions of home screen icons.)

**Comment by arouinfar** [comment]
> • There's little too much 'red' with the apples and car. Perhaps use the blue car?

I agree @pixelzoom. I originally went with carrots for this very reason. I've mocked up a sheared version of the blue car. I don't think it shears quite as well as the red car, but it still looks pretty good.

![image](https://cloud.githubusercontent.com/assets/8419308/19118110/9bf17bc4-8ad8-11e6-8216-b5792bf9276f.png)

> • The car needs a number (see #108) on the home screen icon. If you want to leave it out on the navigation bar icon, we'll need separate artwork. (Navigation bar icons default to scaled down versions of home screen icons.)

If we add the number, we should probably shear it with the body of the car. Otherwise it looks a bit odd.
![image](https://cloud.githubusercontent.com/assets/8419308/19118150/bb166708-8ad8-11e6-8e25-5baeb2e68422.png)

Here's the blue car in the context of the navbar. The number isn't very legible, but I don't think it makes the icon uninterpretable. I could go either way.
![image](https://cloud.githubusercontent.com/assets/8419308/19118447/9bbadec4-8ad9-11e6-9fd1-f54b331146e2.png)

**Comment by ariel-phet** [comment]
These are all looking good to me, and nice color differentiation

**Comment by ariel-phet** [comment]
And my 2 cents, I would do the sheared number on the car (as you said, it still works as an icon)

**Comment by arouinfar** [comment]
Thanks @ariel-phet! We'll go with these icons, and I'll email the assets to @pixelzoom.
![image](https://cloud.githubusercontent.com/assets/8419308/19119319/9fe600ca-8adc-11e6-8046-d51190331328.png)
![image](https://cloud.githubusercontent.com/assets/8419308/19119341/b09149de-8adc-11e6-9c7e-323f1b0e3121.png)

**Comment by arouinfar** [comment]
Asset files have been emailed to @pixelzoom for implementation.

**Comment by pixelzoom** [comment]
Asset files have been received by @pixelzoom for implementation :)

**Comment by arouinfar** [comment]
👍

**Comment by pixelzoom** [comment]
Icons have been integrated. They look great. Closing.

**Comment by arouinfar** [comment]
They do indeed look great in master. Thanks @pixelzoom!
