### ISSUE TITLE
sim credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#55]
@amyh-phet Please provide the desired credits for this sim. 

Here's what we currently have:

``` js
credits: {
      leadDesign: 'Amy Rouinfar',
      softwareDevelopment: 'Dave Schmitz (Schmitzware), Chris Malley (PixelZoom, Inc.)',
      team: '',
      qualityAssurance: '',
      graphicArts: '',
      thanks: ''
    }
```

**Comment by arouinfar** [comment]
Here you go @pixelzoom:

Team: Amy Hanson, Amanda McGarry, Susan Miller, Ariel Paul, Kathy Perkins
QA: Steele Dalton, Amanda Davis
Graphic Arts: Mariah Hermsmeyer

@phet-steele can you please confirm the QA credits?

**Comment by pixelzoom** [comment]
@phet-steele Also OK to leave QA credits open until we get into testing.

**Comment by phet-steele** [comment]
> @phet-steele can you please confirm the QA credits?

Just before publication, yes. Unassigning until then.

**Comment by pixelzoom** [comment]
@phet-steele Since we're close to RC... what are the desired QA credits?

Current QA credits in unit-rates-main.js are:

```js
qualityAssurance: 'Steele Dalton, Amanda Davis',
```

**Comment by pixelzoom** [comment]
Current QA credits in unit-rates-main.js are:

```js
qualityAssurance: 'Steele Dalton, Amanda Davis',
```

**Comment by phet-steele** [comment]
> @phet-steele Since we're close to RC... what are the desired QA credits?

RC testing is still testing that may add more people to the credits, so again I can't tell you the final credits until the sim passes RC. For now, you could at least add Ethan Johnson.

**Comment by phet-steele** [comment]
@pixelzoom, please add Bryce Griebenow to the QA credits while retaining last name alphabetization. Then you can close this.

**Comment by pixelzoom** [comment]
Bryce Grieben added, in master and 1.0.  Final credits shown below.  Closing.

![screenshot_321](https://cloud.githubusercontent.com/assets/3046552/24669155/8cb6bf7a-1926-11e7-966d-2f02d98af873.png)
