### ISSUE TITLE
layout issues with stringTest=double|long

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#56]
Noted in code review #52, related to these checklist items:

> - [ ] Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter 'stringTest=double')
> - [ ] Does the sim layout gracefully handle internationalized strings that are exceptionally long? (run with query parameter 'stringTest=long')

There are some layout issues with `stringTest=double`:

(1) Shopping screen, needs more horizontal space between "Purple Candy" label and icon in combo box. Ditto for some of the vegetables.

![screenshot_23](https://cloud.githubusercontent.com/assets/3046552/19043712/8e6074dc-894e-11e6-9bb0-2f2f00082641.png)

(2) Racing Lab screen, needs horizontal space between "hours" label and edge of panel:

![screenshot_25](https://cloud.githubusercontent.com/assets/3046552/19043758/bab80036-894e-11e6-9bcf-b3cb735355ac.png)

(3) Racing Lab screen, bottom-right control panel overlaps with scene selection radio buttons:

![screenshot_24](https://cloud.githubusercontent.com/assets/3046552/19043738/a8c5e924-894e-11e6-9a7d-c3bc1c190ede.png)

**Comment by pixelzoom** [comment]
Same issues as above with `stringTest=long`, overlap in (3) is more severe.

**Comment by arouinfar** [comment]
@pixelzoom I'll take a look at this and make recommendations for i18n.

The combo box overlaps the remove button even before lengthening the strings, so we'll need to make a few tweaks to the layout regardless. I'll do a more thorough review and report back.
<img width="275" alt="screen shot 2016-10-03 at 11 11 53 am" src="https://cloud.githubusercontent.com/assets/8419308/19046359/37cfcca6-895a-11e6-868f-40dc7d4e6ad6.png">

**Comment by pixelzoom** [comment]
@arouinfar How would you feel about putting the icons to the left of the labels?  Putting icons to the right is always problematic because (1) if unnaturally separates labels from icons, especially when one of the labels is much longer than the others, and (2) there's no support for this is common-code so it requires computing and inserting an explicit spacer, which cause i18n problems like this.

**Comment by arouinfar** [comment]
That's a good suggestion @pixelzoom. Let's move the icons to the left of the strings.  Let's also reduce the size of the icons by ~20%, as they're quite a bit smaller in the mockups.

![image](https://cloud.githubusercontent.com/assets/8419308/19047105/ab43a484-895d-11e6-909a-01e4226870df.png)

**Comment by pixelzoom** [comment]
@arouinfar You mean move the icons to the _left_ of the strings, correct?

**Comment by arouinfar** [comment]
Yes, @pixelzoom. I meant <i>left</i>, but it appears I am directionally challenged...

**Comment by pixelzoom** [comment]
Icons were moved to the left of strings in the combo box.  And other issues are code that is in the process of being replaced and will be deleted.  New code will received its own round of `stringTest` testing.  So closing this issue.
