### ISSUE TITLE
is it necessary to have both uppercase and lowercase versions for words?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#57]
Related to code review #52, related to this checklist item:

> - [ ] Make sure the string keys are all perfect, they are difficult to change after 1.0.0 is published.

In addition to singular and plural versions of some words, the sim also has uppercase and lowercase versions.  For some objects, this means 4 variations that need to be translated for 1 word. For example, here are the string file entries for "apple": 

```
 "apple": {
    "value": "apple"
  },
  "appleCap": {
    "value": "Apple"
  },
  "apples": {
    "value": "apples"
  },
  "applesCap": {
    "value": "Apples"
  },
```

And there are many others that have this similar condition, see below.  I'm not questioning the singular vs plural versions, since those seem to be warranted.  I'm asking about the need for both lowercase and uppercase - because in most PhET sims that I've worked on, we try to use either the lowercase or uppercase version of a word consistently throughout the sim. 

```
  "lemon": {
    "value": "lemon"
  },
  "lemonCap": {
    "value": "Lemon"
  },
  "lemons": {
    "value": "lemons"
  },
  "lemonsCap": {
    "value": "Lemons"
  },
  "orange": {
    "value": "orange"
  },
  "orangeCap": {
    "value": "Orange"
  },
  "oranges": {
    "value": "oranges"
  },
  "orangesCap": {
    "value": "Oranges"
  },
  "pear": {
    "value": "pear"
  },
  "pearCap": {
    "value": "Pear"
  },
  "pears": {
    "value": "pears"
  },
  "pearsCap": {
    "value": "Pears"
  },
  "carrot": {
    "value": "carrot"
  },
  "carrotCap": {
    "value": "Carrot"
  },
  "carrots": {
    "value": "carrots"
  },
  "carrotsCap": {
    "value": "Carrots"
  },
  "cucumber": {
    "value": "cucumber"
  },
  "cucumberCap": {
    "value": "Cucumber"
  },
  "cucumbers": {
    "value": "cucumbers"
  },
  "cucumbersCap": {
    "value": "Cucumbers"
  },
  "potato": {
    "value": "potato"
  },
  "potatoCap": {
    "value": "Potato"
  },
  "potatoes": {
    "value": "potatoes"
  },
  "potatoesCap": {
    "value": "Potatoes"
  },
  "tomato": {
    "value": "tomato"
  },
  "tomatoCap": {
    "value": "Tomato"
  },
  "tomatoes": {
    "value": "tomatoes"
  },
  "tomatoesCap": {
    "value": "Tomatoes"
  },
  "mi": {
    "value": "mi"
  },
  "miles": {
    "value": "miles"
  },
  "milesCap": {
    "value": "Miles"
  },
  "hours": {
    "value": "hours"
  },
  "hoursCap": {
    "value": "Hours"
  },
```

**Comment by pixelzoom** [comment]
Note that for "miles", we also have abbreviates and non-abbreviated versions:

```
  "mi": {
    "value": "mi"
  },
  "miles": {
    "value": "miles"
  },
  "milesCap": {
    "value": "Miles"
  },
```

**Comment by pixelzoom** [comment]
Moving the "miles" issue to a separate issue.

**Comment by pixelzoom** [comment]
Note to self: If we use the same case everywhere, drop the "Cap" key suffix. If we need to have both uppercase and lowercase, then replace "Cap" key suffix with something that will be more meaningful to translators ("Cap" == capital may not be obvious).

**Comment by arouinfar** [comment]
@pixelzoom having both lowercase and uppercase versions of these strings isn't strictly necessary.  If we get rid of the redundancy, I would suggest we keep the uppercase strings. This means that challenge prompts would read like "Cost of 5 Apples?" instead of "Cost of 5 apples?". The question itself is already a bit of a caveman sentence (to minimize string length), so I don't think making the item a proper noun will do any additional harm.

Given that this sim has quite a few strings, I imagine most locales are going to run into testing failure in rosetta due to a long URL (see https://github.com/phetsims/rosetta/issues/100 and https://github.com/phetsims/rosetta/issues/139). I think we should try to reduce the number of strings were possible.

**Comment by arouinfar** [comment]
@pixelzoom let's keep the uppercase version of these strings. As you've pointed out, the singular and plural versions are necessary in this context.

**Comment by pixelzoom** [comment]
OK - keep uppercase, delete lowercase.

**Comment by arouinfar** [comment]
👍

**Comment by pixelzoom** [comment]
It seemed appropriate to use uppercase for object names (Apple, Tomato, etc.), and lowercase for units (hours, miles). @arouinfar Please review in http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.22/unit-rates_en.html

**Comment by arouinfar** [comment]
Looks good!
