### ISSUE TITLE
do we need "miles" and "mi"?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#58]
Related to code review #52.

For "miles", we also have abbreviated and non-abbreviated strings:

```
  "mi": {
    "value": "mi"
  },
  "miles": {
    "value": "miles"
  },
  "milesCap": {
    "value": "Miles"
  },
```

The abbreviation "mi" is used exclusively below the finish line flag in "Racing Lab", and it looks like there's plenty of room to use "miles" there.  Screenshot:

![screenshot_26](https://cloud.githubusercontent.com/assets/3046552/19044595/3b956b1e-8952-11e6-8e1b-fec17bbe87e4.png)

**Comment by arouinfar** [comment]
@pixelzoom good suggestion. Let's change the mile marker label from "mi" to "miles".

**Comment by arouinfar** [comment]
@pixelzoom should I be reassigning you issues like this, or leave them unassigned?

**Comment by pixelzoom** [comment]
@arouinfar Feel free to assign to me.

**Comment by pixelzoom** [comment]
Done, closed.
