### ISSUE TITLE
Typo in "Challanges"

### ISSUE THREAD

**Issue by samreid** [phetsims/unit-rates#6]
It should read "Challenges".  I noticed 6 occurrences across the repo, including but not limited to the filename ChallangesNode.js

**Comment by schmitzware** [comment]
I'm not working on 'Challanges' at the moment, it's all just a place holder for now. But thanks for pointing that out. It will be fixed..

**Comment by schmitzware** [comment]
Sam, I'm not sure where I got around to fixing these 3 early on issues that you put in. They are all fixed though if you want to take a look. (#6, #7, #8)

**Comment by samreid** [comment]
Looks great, thanks! Closing.
