### ISSUE TITLE
scale png files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#60]
Related to code review #52.

The PNG files are currently huge, and the scaling is extreme.  For example, green_candy_bag.png is 516K, and it is scaled by 0.025 (ItemNodeFactory, line 179).  

This causes 2 problems:

(1) The built html file is huge, currently 7.1M. For comparison, balancing-act (which also has 3 screens and many PNG files) is 2M.  Longer download time, longer startup time, and more browser resources.

(2) Relying on the browser to do such extreme scaling is a recipe for poor rendering quality. Firefox (for example) has been historically bad at extreme scaling.

Recommended to re-scale all PNG files, so that scale factor in code is more reasonable (eg. 0.5).

**Comment by arouinfar** [comment]
@pixelzoom the .png files were exported using Illustrator's default settings. Would you like me to re-export them at a more appropriate resolution?

**Comment by pixelzoom** [comment]
@arouinfar Let me determine what an appropriate resolution is, and I'll get back to you.

**Comment by arouinfar** [comment]
Sounds good @pixelzoom!

**Comment by pixelzoom** [comment]
Published [1.0.0-dev.24](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.24/unit-rates_en.html) before I started scaling image files. Size of unit-rates_en.html is 7282206 bytes. Download and start time is unacceptably long.

**Comment by pixelzoom** [comment]
PNG files related to FontAwesome icons have been ignored, since they are going away in #123.
All other PNG files have been scales so that they are scaled by 50% or less in code.

Dev version [1.0.0-dev.25](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.25/unit-rates_en.html) contains the scaled files. Size of unit-rates_en.html is 2015998, a reduction of 72%.  Download and start time is noticeably faster.

@arouinfar please verify that everything looks acceptable.

**Comment by arouinfar** [comment]
Looks good in Chrome and Firefox @pixelzoom. Closing.
