### ISSUE TITLE
items on shelf and scale don't have a pointer cursor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#68]
Code review #52.

Three's no indication that the items on the shelf or scale are draggable, because they don't show the pointer cursor when you mouse over them.   It's not until you actually start dragging that the cursor changes.

@arouinfar Is this a bug or intended behavior?

**Comment by arouinfar** [comment]
@pixelzoom this is a bug. The pointer cursor should be visible when hovering over draggable objects.

**Comment by pixelzoom** [comment]
This was a problem with the old implementation, no plans to fix it.  It will certainly not be an issue in the new implementation. Closing this issue as "will not fix".
