### ISSUE TITLE
Minor updates for annotations

### ISSUE THREAD

**Issue by samreid** [phetsims/unit-rates#8]
I am glad to see the visibility modifiers, such as `// @public (readonly)`, but wanted to point out that the convention is for the modifiers to be hyphenated like `// @public (read-only)`, etc.  The details are listed in the "Coding Style Guidelines" of bit.ly/phet-development-overview

**Comment by schmitzware** [comment]
Thanks Sam - 

Just to point out, At this point, I’m focused on getting functionally complete, not on comments and documentation.  I’ll do (several) more passes on comments and code clean up later.

Cheers,

-Dave

**Comment by samreid** [comment]
Sounds great, there is no need to address these issues now.

**Comment by samreid** [comment]
Looks much better, thanks!  The only thing I'm still seeing for this issue is one occurrence of "read-write" and two occurrences of "readwrite", I think all 3 should be the former.

**Comment by schmitzware** [comment]
Done
https://github.com/phetsims/unit-rates/commit/8db9a4a071abffd097381d69b3bc25d3bf446c15

**Comment by samreid** [comment]
Looks good, thanks! Closing.
