### ISSUE TITLE
is performance acceptable?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#80]
Code review #52, item:

> - [ ] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms)

I don't see any open GitHub issues that indicate performance problems.  And it doesn't make sense to consider this issue "close" until the sim is feature complete (which it's not yet.)

@arouinfar @phet-steele Are you aware of any performance issues for this sim? If so, please describe.

**Comment by phet-steele** [comment]
@pixelzoom I haven't looked at this sim in a long time to be able to know for sure. Would you prefer I look at the sim now for performance issues, or wait until a test cycle?

**Comment by pixelzoom** [comment]
@phet-steele No need to test yet, let's wait until the sim is closer to feature-complete.

**Comment by arouinfar** [comment]
@pixelzoom I haven't been actively looking for performance issues, but I also don't recall running into any issues on my Mac or the iPad Air.

**Comment by pixelzoom** [comment]
No performance issues have been reported, and the new implementation will certainly be subjected to performance testing.  For now, no known issues. Closing.
