### ISSUE TITLE
eraser button looks disabled

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#81]
The color used for the eraser button is ''#f2f2f2'' (gray), and it sure looks like it's grayed out:

![screenshot_36](https://cloud.githubusercontent.com/assets/3046552/19053773/8f47ec88-8979-11e6-9d5b-e2d2fba56a32.png)

Compared to how it will look when the eraser button is disabled (when there's nothing to erase):

![screenshot_37](https://cloud.githubusercontent.com/assets/3046552/19053795/b1e8c960-8979-11e6-955d-fd3addce78cd.png)

The default look of the eraser button (as used in other sims) is:

![screenshot_40](https://cloud.githubusercontent.com/assets/3046552/19053876/04468e04-897a-11e6-9435-06d848808dae.png)

I'm guessing that you changed the default color because of potential conflict with the "edit" buttons.  Shall we investigate other colors that don't make it look disabled when it's enabled? Or use the same color as in other sims?

**Comment by arouinfar** [comment]
@pixelzoom I agree that the difference between the active and disabled eraser button is subtle. We don't want to draw too much attention to the eraser button because it has a rather drastic effect, and students could accidentally lose a lot of work. I didn't notice any usability issues during interviews. 

However, I'm not opposed to giving the active eraser button some color, so long as it's not too bright. Perhaps the light blue used in the "return to start" button would be a good choice.
![image](https://cloud.githubusercontent.com/assets/8419308/19058803/97cab2be-8997-11e6-8597-2d031371cffa.png)

@ariel-phet what do you think?

**Comment by ariel-phet** [comment]
I could go for something in the light blue domain, but I trust your and @pixelzoom judgement

**Comment by arouinfar** [comment]
Thanks @ariel-phet. 

@pixelzoom can you make the active eraser button color match the active "return to start" button color? I'd like to see what it looks like.

**Comment by amanda-phet** [comment]
I've been wondering too if we could revisit this color. What about a white button? I've seen both yellow and white erase buttons in different sims, so we wouldn't be breaking with convention.

**Comment by pixelzoom** [comment]
@amanda-phet I looked through all usages of EraserButton in all sims, I don't see any that have a white button background.

@arouinfar Here's a dev version that uses the same blue (#A9D8FD) as the "restart race" button, let me know if this is acceptable.
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.23/unit-rates_en.html

**Comment by pixelzoom** [comment]
Screenshot with blue eraser button:

![screenshot_201](https://cloud.githubusercontent.com/assets/3046552/19061989/e4f2741c-89b2-11e6-8e99-3b104b1795c3.png)

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I think the eraser button has too much visual weight. I'm going to play with the color a bit in Illustrator and get back to you.

**Comment by arouinfar** [comment]
I think @amanda-phet may have been thinking of the eraser button in Charges and Fields, which is a light gray. However, the eraser button is always active in CAF.

I've tried a few different colors, and I think a pale yellow eraser button looks pretty good. It's clearly active, but not as eye catching as the bright yellow edit buttons. @pixelzoom can you please change the active eraser button to (255, 255, 219)?

![image](https://cloud.githubusercontent.com/assets/8419308/19097137/6f037da2-8a5f-11e6-8672-538c583ab1ee.png)

**Comment by pixelzoom** [comment]
With 'rgb(255, 255, 219)' (muted yellow), it might be mistaken for a disabled edit button. But I've made the change in master.  It looks like your mockup above.

**Comment by arouinfar** [comment]
Good point @pixelzoom. I'll look out for this in the next round of interviews.

**Comment by arouinfar** [comment]
Marking as on-hold until we're ready for the next round of interviews.

**Comment by arouinfar** [comment]
@pixelzoom I noticed that the eraser button in the new shopping screen is gray, and not the pale yellow (255, 255, 219) suggested in https://github.com/phetsims/unit-rates/issues/81#issuecomment-251551924. I don't know if this was already on your radar or not, but I wanted to make sure the button color is migrated over to the new screen so that I can see how it goes in interviews.

**Comment by pixelzoom** [comment]
Good catch - that got overlooked when I factored out colors into one file.  It's now fixed in master.

**Comment by arouinfar** [comment]
Excellent, thanks!

**Comment by pixelzoom** [comment]
I originally opened this issue, and thought that the gray used for the eraser button made it look disabled.  Not I'm feeling differently.  The pale yellow currently used for the eraser button _really_ makes it look disabled, because of its proximity to the yellow edit buttons.  And with the exception of the edit buttons, all other buttons are `'rgb( 242, 242, 242 )'`.  So I feel like our best bet is to start by also using `'rgb( 242, 242, 242 )'` for the eraser button, and watch for problems with that in interviews.   

@arouinfar your thoughts?

**Comment by arouinfar** [comment]
Sounds good to me @pixelzoom. Let's revert to the color of the eraser button to `'rgb( 242, 242, 242 )'`. I'll still look out for usability issues in the interviews, regardless of the final button color.

**Comment by pixelzoom** [comment]
Button color changed in versions > 1.0.0-dev.49.

**Comment by pixelzoom** [comment]
@arouinfar did you notice any problem with this in interviews? Did students use the eraser button?

**Comment by arouinfar** [comment]
@pixelzoom this batch of students didn't really leverage the DNL that much, so they didn't have a reason to use the eraser button. I learned after the fact that BVSD doesn't introduce number lines or DNL representations until middle school, and two of the students were in 5th grade and the other was in 7th grade, but a bit behind in math. 

Students did use the scale refresh button, which is also gray. However, I'd have to re-review the first round of interviews to see if they used the eraser button (but I think they did).

**Comment by arouinfar** [comment]
Scrubbing through the screen capture of the first interview, I quickly stumbled across use of the gray eraser button. I think we can go ahead and close this issue.
