### ISSUE TITLE
Disable "reset shelf" button when shelf is in it's initial state

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#86]
From #54 (Outstanding issues):

I said:

>  Disable "Return to shelf" button when there's nothing on the scale

**Comment by pixelzoom** [comment]
As I've become more familiar with this button, I've come to realize that it does more than just return items to the shelf.  It also puts any items that are in the shelf back into bags.  

Consider this scenario:

![screenshot_123](https://cloud.githubusercontent.com/assets/3046552/22159740/8eb47daa-deff-11e6-8d41-93067f928a72.png)

If we disable the button when there's nothing on the scale, then we can't reset things to bags in the above scenario.

Another scenario:

![screenshot_125](https://cloud.githubusercontent.com/assets/3046552/22159983/ad6fa836-df00-11e6-94f4-c12a173d0f7d.png)

In this case, the "clear scale" button doesn't just clear the scale, it also bags the loose oranges that are on the shelf.

@arouinfar There are two options:

(1) Leave the button enabled at all times.

(2) Change the button to a 'reset' button, disabled when the shelf+scale is in its initial state.

Imo, option (2) is more appropriate, because this button is _not_ just clearing the scale; it is resetting both the shelf and scale to their initial state. Here's what that might look like:

![screenshot_124](https://cloud.githubusercontent.com/assets/3046552/22159940/779a3ee2-df00-11e6-8170-9fe43ba9dcae.png)

**Comment by pixelzoom** [comment]
I'm working on this now, so high priority.

**Comment by arouinfar** [comment]
> I've come to realize that it does more than just return items to the shelf. It also puts any items that are in the shelf back into bags.

The original spec did not include putting items back into the bags, so I guess it was technically a bug in the original implementation. However, it seemed handy to return items to the bags (but the original spec didn't include a way to do this), so no issue was logged. 

The behavior in option (2) sounds more reasonable to me. However, I don't think we should have two reset buttons visible on the screen, particularly because reset typically acts globally. Instead, we could keep the artwork as-is (and update the behavior) or use an alternative icon. I think the refresh icon used in the question refresh button is a good option. We would still have a repeated icon on screen, but both are in close proximity to items they effect. I also don't think refresh has the same global feel that reset does.

That said, I don't have a strong preference for either the return arrow or refresh icon, so I think I'll leave it for @pixelzoom to decide. No matter which artwork we go with, the button would be disabled when the shelf+scale is in its initial state.

**Comment by pixelzoom** [comment]
> I don't think we should have two reset buttons visible on the screen, particularly because reset typically acts globally

Not true. We have ResetButton and ResetAllButton in common code.  They use the same icon. ResetButton is for resetting specific things. RestAllButton is for resetting the entire screen, and is differentiated by its consistent orange color. So RestButton was intended specifically for situations like the shelf+scale.

**Comment by pixelzoom** [comment]
... and RestButton was intended specifically for this purpose.

**Comment by pixelzoom** [comment]
As an example, MOTHA uses ResetButton to reset the spectrometer, see screenshot below. Note its proximity to the ResetAllButton.  There have been zero problems with this approach, why is it not applicable in Unit Rates?

![screenshot_129](https://cloud.githubusercontent.com/assets/3046552/22164991/dbf4d0a8-df16-11e6-9329-a363b4a285b7.png)

**Comment by pixelzoom** [comment]
The refresh button is not appropriate to use for this purpose. The semantics of the refresh button is "give me another one", not "reset to initial state".   See for example the "Mystery" screen in Function Builder.  Or the Questions panel in Unit Rates.

**Comment by pixelzoom** [comment]
Internal documentation in common code:

[ResetButton](https://github.com/phetsims/scenery-phet/blob/master/js/buttons/ResetButton.js):

```
4 * A general button, typically used to reset something.
```

[ResetAllButton](https://github.com/phetsims/scenery-phet/blob/master/js/buttons/ResetAllButton.js):

```
4 * Reset All button, typically used to reset everything ('reset all') on a Screen.
```

**Comment by arouinfar** [comment]
> Not true. We have ResetButton and ResetAllButton in common code.

@pixelzoom I have not seen ResetButton used in any published sims. Thank you for including the MOTHA example. However, I think the MOTHA example is a bit different (despite the proximity of the two buttons) for a few reasons.
* ResetButton is located inside of a panel that is closed on startup.
* ResetButton is much smaller than ResetAllButton.

> There has been zero problem with this approach, why is it not applicable here?

While I am not a part of the MOTHA team, I suspect that approach was acceptable for the reasons I listed above. However, MOTHA has not been interviewed on, so there could be usability issues that we're not yet aware of. 

In Unit Rates, both ResetButton and ResetAllButton are always visible, and I think they have a similar visual weight in the screenshot provided in https://github.com/phetsims/unit-rates/issues/86#issuecomment-274139353 (despite a slight size difference) which could lead to usability issues.

I also understand that ResetButton is the semantically appropriate choice here, so I'm willing to use ResetButton if the size is reduced a bit so there's less competition with ResetAllButton. Here's a very rough mockup showing ResetButton with a 30% reduction in size.
![image](https://cloud.githubusercontent.com/assets/8419308/22167971/d41a193c-df26-11e6-8a8f-bfc0c8ff06db.png)

**Comment by arouinfar** [comment]
ResetButton doesn't need to be reduced by exactly 30% @pixelzoom. That's just a ballpark suggestion based on the patched together mockup.

**Comment by pixelzoom** [comment]
Note to self: In case I need to revert to using the `'level_down'` icon, the implementation of `ResetShelfButton` is in unit-rates master, sha 6bb39ebee343aabbf74ef2261be1f11fbae801f1.

**Comment by pixelzoom** [comment]
Changed to `ResetButton` with approximate size and placement as shown in https://github.com/phetsims/unit-rates/issues/86#issuecomment-274200179.

The button currently does nothing, so leaving this issue open until I implement the desired listener (reset shelf and scale to initial state) and disabling (disable when shelf and scale are in initial state).

**Comment by pixelzoom** [comment]
In the code, I'm now referring to this button as `resetShelfButton`.  It resets the shelf to it's initial state, which may include moving things off the scale _and_ putting items back into bags.

**Comment by pixelzoom** [comment]
Rolled this issue into https://github.com/phetsims/unit-rates/issues/156, closing.
