### ISSUE TITLE
fade between scenes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#88]
From #54 (Outstanding issues):

I said:

> When switching scenes (1 vs 2 cars), should the 2nd car's UI elements fade in/out (ala scene changes in hookes-law)?

Your call @arouinfar.

**Comment by arouinfar** [comment]
Yes, please do this @pixelzoom. I think it would be a nice touch.

**Comment by pixelzoom** [comment]
Sure would be nice if this scene animation behaved like the first screen of Hooke's Law. That is, the 1-car scene had the track vertically centered on the screen. Then switching to 2-car scene would move the track 1 up, and fade in track 2 below.  Switching back to 1-car would face track 2 out, then move track 1 down.  But there doesn't appear to be screen real estate to do this, because of where the "Play" and "Restart" buttons are located.  That particular animation makes it very clear that track 1 is the same instance in both scenes.

@arouinfar your thoughts?

**Comment by pixelzoom** [comment]
Changing the title of this issue to "fade between scenes", since fading may also be desirable on the first 2 screens.

On the Shopping and Shopping Lab screens, each scene has its own state, and each item in a scene has its own state.  Should we fade between fruits/vegetables/candy scenes? Should we fade between items?

**Comment by arouinfar** [comment]
@pixelzoom could we center-align the top track with the "start race" and "return to start" buttons in the 1-car scene, and then scoot it up a bit for the two-car scene?
<img width="1023" alt="screen shot 2016-10-04 at 9 45 14 pm" src="https://cloud.githubusercontent.com/assets/8419308/19100438/0442a66a-8a7c-11e6-87a8-b15f0458e224.png">

<img width="1025" alt="screen shot 2016-10-04 at 9 45 26 pm" src="https://cloud.githubusercontent.com/assets/8419308/19100424/fa0119fc-8a7b-11e6-93ff-fb249628a875.png">

In the Shopping and Shopping Lab screens, switching between scenes or combo box items completely changes the item/scenario. The fading animation seems less necessary for the first two screens, though it would be a nice touch. However, in the Racing Lab screen, we're adding an extra item (the 2nd car) so I think the animation would be more critical.

**Comment by pixelzoom** [comment]
Let's discuss scene transitions in person. How/whether we do it has big implications for whether each scene has its own UI components, or whether there's one set of UI components that changes based on the scene (the current implementation).

**Comment by arouinfar** [comment]
Sounds good @pixelzoom. I believe we'll be on the schedule for design meeting tomorrow, so we can discuss then.

**Comment by arouinfar** [comment]
Discussed in 10/6/16 design meeting. No animated transitions are necessary. Closing.
