### ISSUE TITLE
disable "return to start" button, rather than making it invisible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#90]
From #54 (Outstanding issues):

I said:

> Disabling the "return to start" button, rather than making it invisible, would be more PhET-like.

@arouinfar said:

> Good suggestion. I agree.

@schmitzware added:

> Disabling the "return to start" button, rather than making it invisible, would be more PhET-like. This was a design decision though I didn't bring up your point (not really being aware of it, honestly)

**Comment by pixelzoom** [comment]
@arouinfar Please review in http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.22/unit-rates_en.html

**Comment by arouinfar** [comment]
@pixelzoom the "return to start" button should activate as soon as "go" is pressed. It allows users to send the car back to the starting line, even without finishing the race.

**Comment by pixelzoom** [comment]
OK, will do.  FYI, previously the button didn't become visible until the race finished.  So I implemented the same behavior with enabled instead of visible.  So this is going to be a little more involved for me to fix.

**Comment by pixelzoom** [comment]
The described behavior is implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.47/unit-rates_en.html?showAnswers&randomEnabled=false

(See 1.0.0-dev.47 caveats in https://github.com/phetsims/unit-rates/issues/92#issuecomment-280058069)

@arouinfar please review. Issues #90, #92 and #93 are intertwined, so you may wish to review them together.

**Comment by arouinfar** [comment]
#90, #92, and #93 all look great! Thanks @pixelzoom.
