### ISSUE TITLE
fix behavior of "start race" button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#92]
From #54 (Outstanding issues):

I said:

> "Start race" button should be disabled when cars are at finish line.

@arouinfar said:

> Not exactly... we discussed this in a recent meeting, but unfortunately I can't find it in the notes. We discussed two different behaviors. If "return to start" is pressed, the car returns to the staring line but remains static. If "go" is pressed, the car returns to the start and immediately starts repeating the race.

**Comment by pixelzoom** [comment]
@arouinfar I'm still unclear on the behavior of this button in several scenarios. Please clarify for each of these scenarios:

(1) The user presses the start button. The icon on the button changes to "stop". The race completes.  Does the icon on the button remain "stop"?  Is the button disabled?  If it's not disabled, what happens when the user presses it? 

(2) The user presses the start button. The icon on the button changes to "stop".  Before the race is completed, the user presses the the "restart race" button, and the cars return to the start line.  Does the race start automatically? Does the icon on the button remains "stop"?   Or does the icon on the button change to "start", and the user must press the button to start the race?

(3) The user changes the scene (1 vs 2 cars).  Does this stop the race and move the cars to the starting line?

(4) A race is in progress. The user changes one of the rate spinners.  Does this stop the race and move the cars to the starting line?

(5) A race is in completed, both cars are at the finish line. The user changes one of the rate spinners.  Does this stop the race and move the cars to the starting line?

**Comment by arouinfar** [comment]
Excellent questions @pixelzoom. Here are my recommendations.

(1) The icon on the button returns to "start" when race has completed (both cars at finish line). If "start" is pressed, the cars return to the starting line and immediately begin the racing again. If "return" is pressed, cars return to staring line, but do not move.

(2) If "return" is pressed mid-race (at least one car is still moving) the cars return to the starting line, and the start/stop button will display the "start" icon. The cars will not race again until "start" is pressed.

(3) & (4) Current race stops, both cars move to the starting line, and stop/start button changes to "start" icon.

(5) Changing a rate after the race has finished (both cars at finish line) doesn't necessarily need to move the cars back to the starting line. However, I think it feel more consistent if any change to the rate spinner, regardless of the state of the race, returned the cars to the starting line.

**Comment by pixelzoom** [comment]
The described behavior is implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.47/unit-rates_en.html?showAnswers&randomEnabled=false

@arouinfar please review. Issues #90, #92 and #93 are intertwined, so you may wish to review them together.

**Comment by pixelzoom** [comment]
I should have mentioned that 1.0.0.-dev.47 is not feature complete. This functionality is missing
• car speed is not calibrated, and not affected by rate
• timer is not calibrated
• no indicator appears on the number line to show car position during race
• no marker is created when race completes

That said, the functionality that _is_ implemented is sufficient to verify issues #90, #92 and #93.

**Comment by arouinfar** [comment]
👍
