### ISSUE TITLE
enabled/disable UI controls based on state of race

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/unit-rates#93]
From #54 (Outstanding issues):

@schmitzware said:

> - Need to disable/enable 1/2 car selection buttons on race start/finish
> - Interacting with any UI component needs to stop the race and reset it to the beginning.

... and possibly other UI controls.

**Comment by pixelzoom** [comment]
Related to my questions in https://github.com/phetsims/unit-rates/issues/92#issuecomment-277828037.  This needs to be specified because I'm working on it now.

**Comment by pixelzoom** [comment]
Unless you had something in mind, here's what I recommend:

1. No controls are disabled while a race is in progress.

2. Changing any of the following stops the current race, moves both cars to the starting line, and changes the start/stop button to the "start" icon:
• scene radio buttons (1 vs 2 cars)
• any rate spinner
• the length of either track

**Comment by arouinfar** [comment]
Thanks for the recommendations @pixelzoom. I completely agree with the behavior you've outlined in https://github.com/phetsims/unit-rates/issues/93#issuecomment-277838141.

**Comment by pixelzoom** [comment]
The described behavior is implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.47/unit-rates_en.html?showAnswers&randomEnabled=false

(See 1.0.0-dev.47 caveats in https://github.com/phetsims/unit-rates/issues/92#issuecomment-280058069)

@arouinfar please review. Issues #90, #92 and #93 are intertwined, so you may wish to review them together.

**Comment by arouinfar** [comment]
👍
